### ISSUE TITLE
[Nhóm#04]-Kiểm tra trang Hỗ trợ sinh viên khi Zoom in lên hơn 200% và bị lỗi ở phần Tiện ích- Ở trang https://tthtsv.ueh.edu.vn/	

### ISSUE THREAD

**Issue by 31181024185** [UEHMonQAQC/ST_K44#106]
a. Web Browser: Google Chrome phiên bản 86.0.4240.183 (Phiên bản Chính thức) (64 bit)
b. Kết quả thực tế : Zoom trang đến 200% xuất hiện lỗi ở phần tiện ích, các tiện ích sắp xếp không cân đối
![screenshot](https://user-images.githubusercontent.com/73493671/98754068-76fbb100-23f8-11eb-8820-76bbd47b2532.png)
b. Kết quả mong đợi : Khi Zoom xuống hoặc lên thì bố cục đồng đều, không chèn lên nhau
c. Các bước phát hiện lỗi:
i. #1 Truy cập vào website vào trang chủ (www.tthtsv.ueh.edu.vn) : Hiển thị giao diện trang chủ
ii. #2 Zoom   trang từ 100% đến 150% : Hiển thị đầy đủ tiêu đề, không bị lỗi font chữ và không chèn lên nhau
iii. #3 Zoom trang đến 200% xuất hiện lỗi ở phần tiện ích, các tiện ích sắp xếp không cân đối
iv. #4 Khi Zoom Max (500%) : Hiển thị đầy đủ tiêu đề, không bị lỗi font chữ và không chèn lên nhau
![screenshot](https://user-images.githubusercontent.com/73493671/98754068-76fbb100-23f8-11eb-8820-76bbd47b2532.png)

**Comment by hungho66** [comment]
lỗi responsive chỉ tính ở các kích thước tiêu chuẩn nhé !
VD : Màn hình desktop 100%, Tablet 100%, mobile 100%,....
