### ISSUE TITLE
[Nhóm#04]- Kiểm tra trang Hỗ trợ sinh viên bị lỗi bố cục về Lịch công tác- Ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024185** [UEHMonQAQC/ST_K44#108]
a. Web Browser: Google Chrome phiên bản 86.0.4240.183 (Phiên bản Chính thức) (64 bit)
b. Kết quả thực tế: Chức năng Lịch công tác sai vị trí  
![2020-11-10_LI](https://user-images.githubusercontent.com/73493671/98689214-4850ec80-239e-11eb-8f05-67c263a0eaca.jpg)
c. kết quả mong muốn: Lịch công tác nằm ở Menu Dropdown 
d.Các bước kiểm tra: 
i. #1 Truy cập trang web Hỗ trợ sinh viên (www.tthtsv.ueh.edu.vn)
i. #2 Di chuyển chuột đến chức năng Lịch công tác (Bên phải màn hình)
![2020-11-10_LI](https://user-images.githubusercontent.com/73493671/98689214-4850ec80-239e-11eb-8f05-67c263a0eaca.jpg)

**Comment by hungho66** [comment]
@31181024020 Không phải lỗi nha
