### ISSUE TITLE
[Nhóm#04]-LỖI CHỮ ĐÈ LÊN NHAU KHI ZOOM 150%- Ở TRANG http://handbook.ueh.edu.vn/#/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K44#110]
a. Web browser: MC edge win10
b. Kết quả thực tế
![test](https://user-images.githubusercontent.com/73508317/98690975-1f315b80-23a0-11eb-957c-56b82677f49d.png)
c. Kết quả mong đợi: không bị tràn đè lên nhau khi zoom lên đúng 150%
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://handbook.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/73508317/98690172-3e7bb900-239f-11eb-97ea-58b3e391a873.png)
ii. #2:  trên thanh menu chọn mục Đồng hành cùng sinh viên/Ký túc xá ueh
iii. #3: Sau khi vô được trang ký túc xá ueh thì zoom lên 150% thì lỗi đè chữ sẽ xuất hiện
![test](https://user-images.githubusercontent.com/73508317/98690975-1f315b80-23a0-11eb-957c-56b82677f49d.png)

**Comment by hungho66** [comment]
lỗi responsive chỉ tính ở các kích thước tiêu chuẩn nhé !
VD : Màn hình desktop 100%, Tablet 100%, mobile 100%,....
