### ISSUE TITLE
[Nhóm#04] - Lỗi chức năng Nhắn Tin, Người Quen, Xoá không thực hiện được - ở trang Online.ueh.edu.vn

### ISSUE THREAD

**Issue by phuongha3108** [UEHMonQAQC/ST_K44#111]
a. Web Browser : Microsoft Edge 86.0.622.63
b. Kết quả thực tế : Button không ấn được
![tempsnip](https://user-images.githubusercontent.com/73510933/98691622-cca46f00-23a0-11eb-9389-56bb18be5c70.png)

c. Kết quả mong đợi : Button có thể ấn được

d. Các bước phát hiện lỗi 

i. #1 Truy cập Online.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73510933/98690051-1c823680-239f-11eb-96a6-0eb1b9996334.png)

ii. #2 Đăng nhập 
![image](https://user-images.githubusercontent.com/73510933/98690130-328ff700-239f-11eb-9ab2-e033018f1b89.png)

iii. #3 Ấn vào Mục Nhắn Tin hoặc Người Quen hoặc Xóa
![tempsnip](https://user-images.githubusercontent.com/73510933/98691622-cca46f00-23a0-11eb-9389-56bb18be5c70.png)

**Comment by hungho66** [comment]
Lỗi bị trùng 
#37
