### ISSUE TITLE
[Nhóm#04] Lỗi giao diện Số Lượng Truy Cập không hiển thị - ở trang Online.ueh.edu.vn

### ISSUE THREAD

**Issue by phuongha3108** [UEHMonQAQC/ST_K44#114]
a. Web Browser : Microsoft Edge 86.0.622.63
b. Kết quả thực tế : Số lượng truy cập không hiển thị
![tempsnip](https://user-images.githubusercontent.com/73510933/98692991-4d179f80-23a2-11eb-81eb-08fecc981897.png)
c. Kết quả mong muốn : Hiển thị số lượng người truy cập trong thời điểm đó
d. Các bước phát hiện lỗi
i. #1 Truy cập Online.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73510933/98692846-25c0d280-23a2-11eb-9128-9888cfc831cc.png)

ii. #2 Ấn Đăng Nhập
![tempsnip](https://user-images.githubusercontent.com/73510933/98692991-4d179f80-23a2-11eb-81eb-08fecc981897.png)

**Comment by hungho66** [comment]
Lỗi bị trùng K41
[https://github.com/UEHMonQAQC/K41/issues/188](url)
