### ISSUE TITLE
[Nhóm#04]-CHỮ BỊ TRÀN KHUNG RA LỀ KHI ZOOM ĐÚNG 150%- Ở TRANG http://handbook.ueh.edu.vn/#/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K44#116]
a. Web browser: MC edge hoặc  cococ 
b. Kết quả thực tế
![s](https://user-images.githubusercontent.com/73508317/98693839-5ce3b380-23a3-11eb-812c-98386d374fc7.png)
c. Kết quả mong đợi: không bị tràn ra ngoài khung chứa
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://handbook.ueh.edu.vn/
![](https://user-images.githubusercontent.com/73508317/98690172-3e7bb900-239f-11eb-97ea-58b3e391a873.png)

ii. #2: trên thanh menu chọn mục Đồng hành cùng sinh viên/Ký túc xá ueh
iii. #3: Sau khi vô được trang ký túc xá ueh thì zoom lên đúng 150% thì lỗi chữ bị tràn khung ra  lề ngoài xuất hiện
![s](https://user-images.githubusercontent.com/73508317/98693839-5ce3b380-23a3-11eb-812c-98386d374fc7.png)

**Comment by hungho66** [comment]
lỗi responsive chỉ tính ở các kích thước tiêu chuẩn nhé !
VD : Màn hình desktop 100%, Tablet 100%, mobile 100%,....
