### ISSUE TITLE
[Nhóm#03] - Kiểm tra data có được lưu khi cửa sổ đóng không - ở trang http://comm.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#117]
a.	Web browers: Trình duyệt Cốc Cốc Phiên bản 90.0.148 (Phiên bản Chính thức) (32 bit) 
b.	Kết quả thực tế: các văn bản điền vào được lưu khi vào lại trang web 
c.	Kết quả mong đợi: thông tin được lưu khi vào lại trang.
d.	Các bước để phát hiện lỗi: 
     i.	#1 truy cập trang web http://comm.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/73529771/98703603-42fb9e00-23ae-11eb-9766-29ed0ecba01f.png)
    ii.	#2 nhập thông tin tìm kiếm vào ô tìm kiếm
![image](https://user-images.githubusercontent.com/73529771/98703680-5444aa80-23ae-11eb-8349-e96a4feb6380.png)
iii.	#3 tìm ra kết quả
![image](https://user-images.githubusercontent.com/73529771/98703715-5eff3f80-23ae-11eb-9be9-384d9cfc0db1.png)
iv.	#4 tắt trang truy cập lại
![image](https://user-images.githubusercontent.com/73529771/98703729-6888a780-23ae-11eb-9943-82c3340d6c68.png)

**Comment by hungho66** [comment]
@31181023031 Không phải lỗi, đây là chức năng
