### ISSUE TITLE
[Nhóm#06]- Lỗi giao diện - Tiêu đề không được canh giữa - ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#12]
a.	Web Browser: Google Chrome 86.0.4240.183
b.	Các bước để phát hiện lỗi:
i.	#1: Truy cập vào trang https://tthtsv.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/73525127/98378505-b9c82c80-2078-11eb-9a84-062719e52660.png)
ii.	#2: Truy cập vào mục Sổ tay sinh viên
![image](https://user-images.githubusercontent.com/73525127/98378543-c0ef3a80-2078-11eb-9bd3-7ed50a03a086.png)
c.	Kết quả thực tế: Tiêu đề Sổ tay sinh viên không được canh giữa
d.	Kết quả mong đợi: Canh giữa tiêu đề

**Comment by baolong0** [comment]
Mình xác nhận **LỖI  KHÔNG HỢP LỆ.**
@31181025700
Have a nice day !
_QA_Bảo Long.
