### ISSUE TITLE
[Nhóm#03] - Lỗi chức năng- Lỗi tìm kiếm không có kết quả - ở trang http://comm.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#120]
a.	Web Browser: Opera version 15.0
b.	Kết quả thực tế: Không hiển thị kết quả theo từ khóa mặc dù có nội dung liên quan
![image](https://user-images.githubusercontent.com/73529771/98713156-d2f31500-23b9-11eb-989f-e6b5c61ad51c.png)
c.	Kết quả mong đợi: Hiển thị danh sách liên quan đến “đối tác” 
d.	Các bước phát hiện lỗi:
     i.	#1: Truy cập trang: http://comm.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73529771/98713458-3b41f680-23ba-11eb-977c-fb7115dace2e.png)
    ii.	#2: Chọn mục Tìm kiếm
![image](https://user-images.githubusercontent.com/73529771/98713553-57de2e80-23ba-11eb-8754-a59de05f3af3.png)
    iii.	#3: Kiểm tra kết quả: Kết quả tìm kiếm "đối tác" 0 / 0
![image](https://user-images.githubusercontent.com/73529771/98713768-9a077000-23ba-11eb-8b2b-8e7f19f0f8af.png)

**Comment by hungho66** [comment]
Đổi từ khóa sẽ tìm kiếm được 
http://comm.ueh.edu.vn/News/SearchResult?searchString=Test
@31181023031
