### ISSUE TITLE
[Nhóm#04]- LỖI CHỮ TRÀN ĐÈ LÊN NHAU KHI ZOOM MÀN HÌNH LÊN 125-150% - ở trang http://handbook.ueh.edu.vn/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K44#126]
a. Web browser: MC edge hoặc côccoc win10
b. Kết quả thực tế
![Annotation 2020-11-11 074408](https://user-images.githubusercontent.com/73508317/98751480-c9d26a00-23f2-11eb-94c4-6124bf4d3f7e.png)
c. Kết quả mong đợi: không bị tràn đè lên nhau
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://handbook.ueh.edu.vn/

![](https://user-images.githubusercontent.com/73508317/98690172-3e7bb900-239f-11eb-97ea-58b3e391a873.png)
ii. #2: Sau đó ta zoom lên 125- 150% thì lỗi chữ  bắt đầu bị tràn đè lên thanh tìm kiếm, logo ueh 
![Annotation 2020-11-11 074408](https://user-images.githubusercontent.com/73508317/98751480-c9d26a00-23f2-11eb-94c4-6124bf4d3f7e.png)

**Comment by hungho66** [comment]
lỗi responsive chỉ tính ở các kích thước tiêu chuẩn nhé !
VD : Màn hình desktop 100%, Tablet 100%, mobile 100%,....
@31181024020
