### ISSUE TITLE
[nhóm#09] - lỗi giao diện - định dạng font chữ - ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#131]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: định dạng không đồng đều.
![ll](https://user-images.githubusercontent.com/73509326/98760754-841f9c80-2406-11eb-83ae-e0668b8bb5fc.PNG)
c. kết quả mong đợi. đingj dạng lại font chữ, canh lề.
d. các bước phát hiện lỗi.
i. #1 truy cập vào trang web [http://daotao.ueh.edu.vn/](http://daotao.ueh.edu.vn/)
ii. #2 trong phần biểu mẫu và cẩm nang sinh viên chọn "cẩm nang sinh viên"
![ttt](https://user-images.githubusercontent.com/73509326/98761066-35263700-2407-11eb-9a4b-5025478d6758.PNG)

**Comment by uyenxinhdep** [comment]
https://github.com/UEHMonQAQC/K42/issues/90
Lỗi bị trùng.
Nhóm tìm lỗi khác giúp mình.
