### ISSUE TITLE
[Nhóm#01] - Lỗi giao diện- click button "trở về" trên trình duyệt trang bị đè chữ khi ở màn hình trang đăng nhập - trang: http://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by iamk1102** [UEHMonQAQC/ST_K44#132]
a. Web Browser: Brave version: Version 1.16.72 Chromium: 86.0.4240.183 (Official Build) (64-bit)
b. Kết quả thực tế: Thông báo yêu cầu sinh viên xác nhận đăng xuất trước đăng nhập với người dùng khác bị đè lên.
![image](https://user-images.githubusercontent.com/71264049/98761692-96023f00-2408-11eb-981c-c921a3178da7.png)

c. Kết quả mong đợi: Không bị lỗi hiển thị 
d. Các bước để phát hiện lỗi:
i. #1: Truy cập thành công vào trang http://online.ueh.edu.vn 
 
![image](https://user-images.githubusercontent.com/71264049/98761700-9a2e5c80-2408-11eb-80ae-7200acb144da.png)

i.	#2. Click button quay lại trên trình duyệt đang dùng
 
![image](https://user-images.githubusercontent.com/71264049/98761705-9d294d00-2408-11eb-8aab-31d93e11b017.png)

i.	#3. 
 
![image](https://user-images.githubusercontent.com/71264049/98761707-a0243d80-2408-11eb-9f99-fb15cdb1b53f.png)

**Comment by tatdoan2560** [comment]
Mình đã xem qua và xác nhận đây là lỗi.
Chúc mọi người buổi tối vui vẻ!
