### ISSUE TITLE
[Nhóm #07] - Lỗi chức năng –Lỗi chức năng thanh tìm kiếm cho ra kết quả sai - ở trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023111** [UEHMonQAQC/ST_K44#139]
a. Web browser: Google Chrome 86.0.4240.183 cho Window 10/8.1/8/7 64 bit.
b. Kết quả thực tế: Thanh tìm kiếm cho ra kết quả không liên quan đến từ khóa "Y tế"
![image](https://user-images.githubusercontent.com/73515797/98796274-c9ab8c00-243d-11eb-99f8-dc55b58afb8b.png)
c. Kết quả mong đợi: Cho ra kết quả việc làm được phân theo ngành liên quan đến từ khóa "y tế" hoặc không có kết quả nào (nếu không có công việc liên quan)
d. Các bước phát hiện lỗi:
i. Truy cập vào trang https://vieclam.ueh.edu.vn/
ii. Gõ từ khóa "y tế" vào thanh tìm kiếm và nhấn Enter 
![image](https://user-images.githubusercontent.com/73515797/98797228-e3010800-243e-11eb-9565-3d8d4bc074a2.png)
iii. Kết quả tìm kiếm sẽ là công việc không liên quan tới từ khóa "y tế" 
![image](https://user-images.githubusercontent.com/73515797/98797420-1d6aa500-243f-11eb-8e71-3cb3af64d01e.png)

**Comment by PhucLuan** [comment]
Xác nhận lỗi
