### ISSUE TITLE
[Nhóm # 07] Lỗi giao diện - Không thể hiện đề mục của trang - ở trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181022249** [UEHMonQAQC/ST_K44#144]
a.Web browser: Phiên bản 86.0.4240.183
b. Thực tế kết quả:  Không thể hiện được cho người dùng biết được mình đang ở trang nào: Các đề mục đổi màu trùng với background hoặc không có.
![0](https://user-images.githubusercontent.com/73516822/98965988-4e310400-253d-11eb-85ff-219c3155e279.jpg).
c. kết quả được mong đợi: Hiển thị đổi màu để người dùng phân biệt và nắm bắt được mình đang ở nội dung nào của trang
 ví dụ: ![1](https://user-images.githubusercontent.com/73516822/98967210-d1068e80-253e-11eb-8573-5f9ef3d34a72.jpg).
d. Các bước phát hiện lỗi: 
#1. truy cập vào trang: https://vieclam.ueh.edu.vn/
![00](https://user-images.githubusercontent.com/73516822/98968442-445cd000-2540-11eb-8744-d8dd33f73f64.jpg).
--> đặt vấn đề: ủa mình đang ở mục nào, liệu đây có phải là trang chủ?
#2. truy cập vào đề mục công việc 
![11](https://user-images.githubusercontent.com/73516822/98968657-884fd500-2540-11eb-812f-9563896fe0e1.jpg).
--> Nhận ra: 2 đề mục khác nhau nhưng giao diện không hiển thị là trang đang ở đề mục nào.

**Comment by PhucLuan** [comment]
Thanh nav đã hỗ trợ chuyển sang trang web khác. Do đó không cần thiết đặt hiệu ứng highlight. Do đó đây không phải lỗi.
