### ISSUE TITLE
[Nhóm # 07] - Lỗi giao diện- Các đề mục trong giao diện không có hiệu ứng hover . trang: https://vieclam.ueh.edu.vn/cong-viec/danh-sach-cong-viec

### ISSUE THREAD

**Issue by 31181022249** [UEHMonQAQC/ST_K44#146]
a.Web browser: Phiên bản 86.0.4240.183
b. Kết quả thực tế: Khi đưa chuột vào đề mục, không có hiện tượng đang đc đề cử.
![2](https://user-images.githubusercontent.com/73516822/98982893-a58d9f00-2552-11eb-87b9-01928e0c89bc.jpg).
c. Kết quả được mong đợi: Hiện thị hiệu ứng đang được chọn khi đưa con trỏ chuột vào đề mục.
d. Các bước phát hiện lỗi: 
#1. Truy cập vào trang:  https://vieclam.ueh.edu.vn/cong-viec/danh-sach-cong-viec
#2. Đưa chuột vào các đề mục để xem có hiện tượng gì xảy ra.
#3. Nhận thấy khi đưa chuột vào đề mục, con trỏ chuột biểu thị hình bàn tay, nghĩa  là đề mục được gắn link và đưa qua lại các đề mục thì chỉ có hình bàn tay, không có một hiệu ứng biểu thị giao diện

**Comment by PhucLuan** [comment]
@31181022249 đây là do trang web không hỗ trợ. Do đó không phải lỗi nhé.
