### ISSUE TITLE
[Nhóm #06] - Lỗi phi chức năng – Hiệu suất tải trang không đạt yêu cầu - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181021429** [UEHMonQAQC/ST_K44#147]
a. Web browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: đạt 35 điểm nằm trong khoảng đỏ (0-49), trang không đạt yêu cầu
![Group 6](https://user-images.githubusercontent.com/73511027/99027964-24a9c400-25a1-11eb-828e-e6a4dd89f386.png)
c. Kết quả mong đợi: Điểm nằm trong khoảng xanh (90-100)
d. Các bước phát hiện lỗi:
i. #1: truy cập trang https://developers.google.com/speed/pagespeed/insights/?hl=vi
ii. #2: Nhập đường link http://ctct.ueh.edu.vn/ vào, chọn bấm phân tích.
![Group 7](https://user-images.githubusercontent.com/73511027/99028226-cf21e700-25a1-11eb-899d-cc88c4558bf2.png)
iii. #3: Đợi tool check, bấm chọn “Máy tính để bàn” để xem kết quả.
![Group 6](https://user-images.githubusercontent.com/73511027/99028233-d3e69b00-25a1-11eb-9da8-5d64118797d0.png)

**Comment by baolong0** [comment]
Mỗi nhóm chỉ được chấp nhận 01 lỗi phi chức năng test bằng TOOL ! 
Nhóm 06 đã được xác nhận lỗi PHI CHỨC NĂNG test bằng tool nên lỗi này không được chấp nhận ! 
@31181021429
