### ISSUE TITLE
[nhóm#09] - lỗi giao diện - nội dung bị tràn ra màng hình - ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#150]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: giao diện không hiển thị hết nội trong khi khoảng trống hai bên vẫn còn thừa.
![ss](https://user-images.githubusercontent.com/73509326/99095284-8735ab00-2607-11eb-9e0a-50020ae74a84.PNG)
c. kết quả mong muốn: hạn chế khoảng trống thừa để hiện đầy đủ nội dung.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web http://daotao.ueh.edu.vn/
ii. #2 click vào thông báo mới.
![cccc](https://user-images.githubusercontent.com/73509326/99095616-f3181380-2607-11eb-84c7-63a5ea7f742c.PNG)
iii. #3 xuống cuoiis trang và click vào "sau".
![ffffffffffff](https://user-images.githubusercontent.com/73509326/99095823-31153780-2608-11eb-8c6a-80baded1235f.PNG)
iv. #4 click vào "thong báo thời gian đăng ký chuyên nghành....".
![aa](https://user-images.githubusercontent.com/73509326/99096025-67eb4d80-2608-11eb-9d1c-03398c506f48.PNG)

**Comment by uyenxinhdep** [comment]
Cuối trang có thanh trượt để xem được toàn bộ nội dung và không bị tràn màn hình.
Đây không phải lỗi, nhóm tìm lỗi khác giúp mình @31181025359
