### ISSUE TITLE
[Nhóm #03] – Lỗi giao diện – Lỗi danh mục trên navbar không được sắp xếp theo một quy chuẩn - ở trang http://www.youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#155]
a. Web Browser: Web Browser: Microsoft Edge (86.0.622.63)
b. Kết quả thực tế: Danh mục trên navbar không được sắp xếp theo một quy chuẩn
![image](https://user-images.githubusercontent.com/73529771/99144895-8ac74180-269c-11eb-94ce-1ac5e83c5d0f.png)
c. Kết quả mong đợi: Danh mục được sắp xếp theo quy chuẩn nhất định
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://kqm.ueh.edu.vn/ 
ii. #2: Chọn “CLB, Đội,Nhóm”
ii. #3: Chọn “CLB, Đội,Nhóm học thuật” hoặc “CLB,Đội,Nhóm sở thích”
![image](https://user-images.githubusercontent.com/73529771/99144904-961a6d00-269c-11eb-9d5b-53d0b1a47c13.png)
![image](https://user-images.githubusercontent.com/73529771/99144906-97e43080-269c-11eb-9cc8-359e8f1f6eda.png)

**Comment by hungho66** [comment]
Cập nhật lại mô tả @31181023031 
Không phải lỗi
