### ISSUE TITLE
[Nhóm#7] Lỗi giao diện - Lỗi fone chữ trang Phòng Đào Tạo

### ISSUE THREAD

**Issue by hai-quan-tran** [UEHMonQAQC/ST_K44#158]
a. web browser : Google Chrome
b. kết quả thực tế: 
![image](https://user-images.githubusercontent.com/73516200/99162357-a2033f00-272f-11eb-994a-7bfbac024192.png)
c. kết quả mong đợi: không bị sai fone chữ, thống nhất 1 fone chữ 
d. các bước để phát hiện lỗi:
i. #1 Truy cập vào trang web: http://daotao.ueh.edu.vn/
ii. #2 Ở mục biểu mẫu và cẩm nang sinh viên, click chọn Cẩm nang sinh viên 
iii. #3 Lỗi nằm cuối trang 
![image](https://user-images.githubusercontent.com/73516200/99162489-e3e0b500-2730-11eb-9b03-00bff69db514.png)

**Comment by PhucLuan** [comment]
@31181021071 Trùng với lỗi #28, nhắc nhở: đặt tiêu đề phải kèm đường link trang web
