### ISSUE TITLE
[Nhóm #03] – Lỗi chức năng – Lỗi luồng thao tác không đúng - ở trang http://www.youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#160]
a.	Web Browser: Opera version 15.0
b.	Kết quả thực tế: (không link đến trang fanpage trên facebook khi click chuột vào icon Facebook)
![image](https://user-images.githubusercontent.com/73529771/99181427-15717480-2761-11eb-8027-8e32ff0cdb0e.png)
c.	Kết quả mong đợi: Link đến trang web fanpage facebook
d.	Các bước phát hiện lỗi:
     i.	#1: Truy cập trang: http://youth.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73529771/99181436-27531780-2761-11eb-9ef4-9a6fdac861b4.png) 
    ii.	#2: Chọn icon facebook
![image](https://user-images.githubusercontent.com/73529771/99181444-38038d80-2761-11eb-9cab-1367fbbe38ca.png)

*Không link được qua fanpage facebook

**Comment by hungho66** [comment]
Lỗi trùng
[https://github.com/UEHMonQAQC/K41/issues/134](url)
@31181023031
