### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - tự đăng thoát tài khoản - ở trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#164]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: tự động đăng thoát tài khoản khi chuyển sang tag khác trong trang.
![bb](https://user-images.githubusercontent.com/73509326/99188956-5aad9a80-2791-11eb-9c70-aaf455aaf0ae.PNG)
c. kết quả mong đợi: tài khoản không tự thoát khi chưa được người dùng đăng thoát.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web [http://online.ueh.edu.vn/](http://online.ueh.edu.vn/)
ii. #2 đăng nhập người dùng là sinh viên bằng tài khoản sinh viên.
![rr](https://user-images.githubusercontent.com/73509326/99189168-909f4e80-2792-11eb-84c4-2e028d9f88e1.PNG)
iii. #3 click vào trang chủ sau khi đăng nhập thành công.
![qqqqq](https://user-images.githubusercontent.com/73509326/99189195-b3c9fe00-2792-11eb-9b98-79c22b2218b0.PNG)
iv. #4 hệ thống tự đăng thoát người dùng
![bb](https://user-images.githubusercontent.com/73509326/99189235-d0663600-2792-11eb-8d43-d10305a14028.PNG)

**Comment by uyenxinhdep** [comment]
https://github.com/UEHMonQAQC/ST_K44/issues/82
Lỗi bị trùng.
Nhóm tìm lỗi khác giúp mình @31181025359
