### ISSUE TITLE
[Nhóm #02] - Lỗi giao diện- hover đổi màu nhưng không click vào được ở trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181021258** [UEHMonQAQC/ST_K44#165]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: hover đổi màu làm người dùng nhầm tưởng là có thể click vào được 
![image](https://user-images.githubusercontent.com/73569145/99206136-37183d80-27ed-11eb-8b7f-85d071ccab23.png)
c. Kết quả mong đợi: khi hover vào không đổi màu nữa
d. Các bước để phát hiện lỗi:
i. #1: truy cập vào trang online.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73569145/99206151-3ed7e200-27ed-11eb-8020-f43ec6b33207.png)
ii. #2: chọn đăng nhập và nhập tài khoản mật khẩu
![image](https://user-images.githubusercontent.com/73569145/99206167-45fef000-27ed-11eb-8f95-ab401c66f877.png)
iii. #3: chọn vào mục đăng ký chuyên ngành
![image](https://user-images.githubusercontent.com/73569145/99206184-557e3900-27ed-11eb-8ae0-f42396665498.png)
iv. #4: hover đổi màu làm người dùng nhầm tưởng là có thể click vào được 
![image](https://user-images.githubusercontent.com/73569145/99206201-5e6f0a80-27ed-11eb-930d-13f7a5304b6c.png)

**Comment by tatdoan2560** [comment]
Mình đã kiểm tra và xác nhận đây là lỗi Giao diện nhé.
Cảm ơn mọi người !
