### ISSUE TITLE
[nhóm#02] - lỗi phi chức năng - xét tính khả thi của trang http://taichuc.ueh.edu.vn/trang-chu

### ISSUE THREAD

**Issue by 31181021258** [UEHMonQAQC/ST_K44#171]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: 
Trang web có nhiều vấn đề chính về bố cục hoặc hiệu suất ở trình duyệt : IE 11, Safari 13 và ở phiên bản IOS 12, Android 85
Trang web có nhiều vấn đề nhỏ về bố cục hoặc hiệu suất ở hầu hết tất cả các trình duyệt và phiên bản IOS 12, 13 14, Android 85,86
![image](https://user-images.githubusercontent.com/73569145/99208940-7eee9300-27f4-11eb-9689-ec6efba72f4f.png)
c. Kết quả mong đợi: khắc phục được các lỗi về hiệu xuất và giao diện 
d. Các bước để phát hiện lỗi:
i. #1: truy cập vào trang web https://www.powermapper.com/products/sortsite/checks/browser-compatibility/
![image](https://user-images.githubusercontent.com/73569145/99208953-87df6480-27f4-11eb-8a15-ecb67da7a457.png)
ii. #2: nhập url của trang tại chức vào Test a site
![image](https://user-images.githubusercontent.com/73569145/99208960-8f067280-27f4-11eb-9948-f3dbb8232de2.png)
iii. #3: nhấp vào nút test site
iv. #4: sau khi ra kết quả nhấn vào view report
![image](https://user-images.githubusercontent.com/73569145/99208969-9594ea00-27f4-11eb-9043-dd8e88fb09a5.png)
v. #5: nhấn vào compatibility
![image](https://user-images.githubusercontent.com/73569145/99208992-9d548e80-27f4-11eb-99b1-f69968ca884a.png)
vi. #6: hiện thị kết quả
![image](https://user-images.githubusercontent.com/73569145/99209000-a34a6f80-27f4-11eb-8881-b37ff8ea441d.png)

**Comment by tatdoan2560** [comment]
Mình đã xem qua và xác nhận đây là lỗi.
Cảm ơn mọi người !
