### ISSUE TITLE
[nhóm#05] - Lỗi phi chức năng – Tốc độ phản hồi của trang chậm ở giao diện máy tính - ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024008** [UEHMonQAQC/ST_K44#172]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: Tốc độ phản hồi trang chậm
![1](https://user-images.githubusercontent.com/73530783/99209078-de4ca300-27f4-11eb-9239-b400ee3b8cfb.jpg)
c. Kết quả mong đợi: tốc độ phản hồi trang sẽ nhanh hơn
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://developers.google.com/speed/pagespeed/insights/
ii. #2: Nhập địa chỉ của trang https://tthtsv.ueh.edu.vn/
iii. #3: Nhấn chọn nút phân tích

**Comment by baolong0** [comment]
Lỗi trùng ! 
https://github.com/UEHMonQAQC/ST_K44/issues/142 
@31181024008
