### ISSUE TITLE
[nhóm#05] - Lỗi  chức năng – link liên kết không truy cập được - ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024008** [UEHMonQAQC/ST_K44#174]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: Trang web vẫn ở lại trang Giới thiệu mà không sang trang UEH Café
c. Kết quả mong đợi: Truy cập được link.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web https://tthtsv.ueh.edu.vn/
ii. #2 chọn mục Giới thiệu
![2](https://user-images.githubusercontent.com/73530783/99209719-60899700-27f6-11eb-9750-7df5f9768e01.jpg)
iii. #3 Kéo xuống dưới cùng ở mục liên kết Web click vào UEH Café
![3](https://user-images.githubusercontent.com/73530783/99209825-ae060400-27f6-11eb-91ce-ea1dc2d2b974.jpg)

**Comment by baolong0** [comment]
Lỗi bị trùng !!!


https://github.com/UEHMonQAQC/ST_K44/issues/71
