### ISSUE TITLE
[Nhóm#07] Lỗi giao diện - Lỗi canh lề không đều ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by hai-quan-tran** [UEHMonQAQC/ST_K44#181]
a. web browser: Google Chrome
b. kết quả thực tế: canh lề không đều 
![image](https://user-images.githubusercontent.com/73516200/99229924-3e593e80-2821-11eb-883a-0304abf90c6b.png)
c. kết quả mong đợi: canh lề thẳng hàng 
d. các bước để phát hiện lỗi
i. #1 truy cập vào trang http://daotao.ueh.edu.vn/
ii. #2 click vào Câu hỏi thường gặp ở bên trái
iii. #3 click vào Những câu hỏi thường gặp về kết quả học tập
![image](https://user-images.githubusercontent.com/73516200/99230157-8d06d880-2821-11eb-8690-40f6529e964a.png)
iv. #4 kéo đến cuối trang 
![Untitled](https://user-images.githubusercontent.com/73516200/99230245-b0318800-2821-11eb-836e-2233f7e67096.png)

**Comment by PhucLuan** [comment]
@31181021071 đây là do người viết muốn nhấn mạnh nội dung nên thụt đầu dòng, không phải do trang web hiển thị bị lỗi. Do đó không phải lỗi nhé.
