### ISSUE TITLE
[nhóm#02] - lỗi phi chức năng – Lỗi trễ màn hình - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020316** [UEHMonQAQC/ST_K44#184]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: Có sự trễ giữa các button trên thanh bar khi lia chuột liên tục giữa các button
![image](https://user-images.githubusercontent.com/72690360/99246135-5d62cb00-2837-11eb-9700-94c69c4b34de.png)

c. Kết quả mong đợi: Thay đổi nhanh giữa các button
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang http://ctct.ueh.edu.vn/

ii. #2: lia chuột liên hồi giữa các button trên thanh navbar
![image](https://user-images.githubusercontent.com/72690360/99246451-e7ab2f00-2837-11eb-87c1-193d5dbca44c.png)
![image](https://user-images.githubusercontent.com/72690360/99246469-ebd74c80-2837-11eb-8bc0-9d8b72f3e688.png)
![image](https://user-images.githubusercontent.com/72690360/99246524-027da380-2838-11eb-98d4-e02dfb7328be.png)

iii. #3: Sau đó các button sẽ sáng lên gây ảnh hưởng không phân biệt được trang đang truy cập
![image](https://user-images.githubusercontent.com/72690360/99246707-5a1c0f00-2838-11eb-9214-e34ac4702d03.png)

**Comment by tatdoan2560** [comment]
Mình đã xem qua và xác nhận đây là lỗi.
Cảm ơn mọi người !
