### ISSUE TITLE
[Nhóm#08]-Lỗi Phi Chức Năng - Kiểm tra độ tin cậy của trang web (http://ibr.ueh.edu.vn/)

### ISSUE THREAD

**Issue by namnguyenphuong355** [UEHMonQAQC/ST_K44#185]
a. Web Browser : Google Chrome cho Windows 10 -- web test--http://ibr.ueh.edu.vn/
b. Kết quả thực tế: Trang web được đánh giá là không độc lại vì phần mềm không tìm thấy các mối đe dọa trên trang web
![phi 1](https://user-images.githubusercontent.com/73516957/99257958-6c9f4400-284a-11eb-90d3-1aa0399581e8.PNG)
![phi 2](https://user-images.githubusercontent.com/73516957/99257967-6e690780-284a-11eb-8521-83c5fb556f2a.PNG)
![phi 3](https://user-images.githubusercontent.com/73516957/99257974-70cb6180-284a-11eb-994e-b84a345d9502.PNG)
![phi 4](https://user-images.githubusercontent.com/73516957/99257981-73c65200-284a-11eb-8063-338c3e9d90ad.PNG)
c. kết quả mong đợi: Trang web an toàn
d. các bước kiểm tra:
#1- vào trang web: https://www.urlvoid.com/
#2- Nhập url này vào form kiểm tra: http://ibr.ueh.edu.vn/
![demo](https://user-images.githubusercontent.com/73516957/99258423-23032900-284b-11eb-956c-0763df1d7980.PNG)

**Comment by PhucLuan** [comment]
@31181023044  Các bạn chú ý giúp mình, issue là phần các bạn báo lỗi, không phải thực hiện test case rồi mô tả lại. Kết quả test bình thường sao các bạn lại báo lỗi?
![image](https://user-images.githubusercontent.com/54372656/99261604-84c59200-284f-11eb-8541-446608309655.png)

**Comment by PhucLuan** [comment]
Các bạn vui lòng không assign thầy trước khi mình xác nhận đây là lỗi nhé. Cảm ơn các bạn.
