### ISSUE TITLE
[Nhóm#08]-Lỗi Phi Chức Năng - Kiểm tra độ tốc độ của trang web(http://nnkt.ueh.edu.vn/)

### ISSUE THREAD

**Issue by namnguyenphuong355** [UEHMonQAQC/ST_K44#186]
a. Web Browser : Google Chrome cho Windows 10 -- web test --http://nnkt.ueh.edu.vn/
b. Kết quả thực tế: Trang web được đánh giá là có tốc độ bình thường, ổn định. chi tiết xem ảnh bên dưới
----Kết quả---
![fi2](https://user-images.githubusercontent.com/73516957/99259768-11228580-284d-11eb-904c-691186873017.PNG)
----Phân tích thành phần của trang web----
![al fi3](https://user-images.githubusercontent.com/73516957/99259777-18499380-284d-11eb-8ea3-fdb27a729a9c.PNG)
----Biểu đồ tốc độ khi truy xuất các file yêu cầu ----
![fi4](https://user-images.githubusercontent.com/73516957/99259786-1d0e4780-284d-11eb-8d4c-31a17e4b231b.PNG)
c. Kết quả mong đợi: Trang web có tốc độ ổn định hoặc nhanh
d. Các bước kiểm tra:
#1- truy cập link test  :https://tools.pingdom.com/
#2- Nhập link http://nnkt.ueh.edu.vn/ vào form và bấm start test:
![fi 1](https://user-images.githubusercontent.com/73516957/99260143-95750880-284d-11eb-8670-f7d2ef9bb988.PNG)

**Comment by PhucLuan** [comment]
@31181023044  Tốc độ bình thường, ổn định sao lại tính là lỗi? Dựa trên mô tả của nhóm thì đây không phải là lỗi nhé. Mình chưa xác nhận là lỗi thì các bạn vui lòng khoan Assign thầy giúp mình nhé, việc assign là của QA, các bạn để ý cho những lần sau giúp mình, thanks.
![image](https://user-images.githubusercontent.com/54372656/99261006-b9851980-284e-11eb-9826-9e1dc9cbb463.png)

**Comment by PhucLuan** [comment]
@31181023044 format tiêu đề vẫn sai nhé nhóm 8, mình đã nhắc nhở các bạn rất nhiều lần rồi, các bạn chú ý dùm mình. Trên tiêu đề phải để là các bạn test ở đường link của trang web nào. Nếu vẫn tiếp tục sai mình sẽ note lại và trừ điểm nhé.
