### ISSUE TITLE
[Nhóm#04] - Kiểm tra trang lịch công tác khi Zoom in lên hơn 200% và lỗi thông tin trang- Ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024185** [UEHMonQAQC/ST_K44#198]
a. Web Browser: Google Chrome phiên bản 86.0.4240.183 (Phiên bản Chính thức) (64 bit)
b. Kết quả thực tế: Zoom trang đến 250% xuất hiện lỗi ở phần lịch công tác, các thông tin sắp xếp không cân đối
![screenshot6](https://user-images.githubusercontent.com/73493671/99290928-9ae44a00-2871-11eb-8590-bf6c0ea608a9.png)

c. Kết quả mong muốn: Khi Zoom xuống hoặc lên thì bố cục đồng đều, không chèn lên nhau
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang Việc làm (www.vieclam.ueh.edu.vn)
ii. #2 Nhấn chọn lịch công tác trên thanh chức năng
iii. #3 Chọn một lịch công tác bất kỳ
iv. #4 Zoom in 150% đến 200%: Đã xuất hiện lỗi nhưng chưa nhiều
v. #5 Zoom  in 250%: Các thông tin bị chèn lên nhau, sắp xếp không đều
![screenshot6](https://user-images.githubusercontent.com/73493671/99290928-9ae44a00-2871-11eb-8590-bf6c0ea608a9.png)

**Comment by hungho66** [comment]
lỗi responsive chỉ tính ở các kích thước tiêu chuẩn nhé !
VD : Màn hình desktop 100%, Tablet 100%, mobile 100%,....
@31181024020
