### ISSUE TITLE
[Nhóm#04] - Kiểm tra trang lịch công tác và lỗi bố cục khi xem lịch công tác- Ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024185** [UEHMonQAQC/ST_K44#199]
a. Web Browser: Google Chrome phiên bản 86.0.4240.183 (Phiên bản Chính thức) (64 bit)
b. Kết quả thực tế: Bố cục không cân xứng
![screenshot8](https://user-images.githubusercontent.com/73493671/99292488-daac3100-2873-11eb-9a58-5ec84f6def15.png)

c. Kết qua mong muốn: Bố cục cân xứng hơn
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang Việc làm (www.vieclam.ueh.edu.vn)
ii. #2 Nhấn chọn lịch công tác trên thanh chức năng
iii. #3 Chọn một lịch công tác bất kỳ
![screenshot8](https://user-images.githubusercontent.com/73493671/99292488-daac3100-2873-11eb-9a58-5ec84f6def15.png)

**Comment by hungho66** [comment]
Lỗi trùng
@31181024020 
#197
