### ISSUE TITLE
[Nhóm #04] - Kiểm tra trang Tư vấn cá nhân khi phóng to hơn 175% và lỗi hiển thị chức năng bên trái -Ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024185** [UEHMonQAQC/ST_K44#201]
a. Web Browser: Google Chrome phiên bản 86.0.4240.183 (Chính thức phiên bản) (64 bit)
b. Kết quả thực tế: Zoom trang đến 175%  xuất hiện lỗi hiển thị ở các chức năng bên trái
![screenshot10](https://user-images.githubusercontent.com/73493671/99295093-8d31c300-2877-11eb-9a1c-81cc90009445.png)
c. Kết quả mong muốn: Hiển thị các chức năng bên trai khi Zoom in
d. Các bước phát hiện lỗi:
i. # 1 Truy cập trang Hỗ trợ sinh viên ( www.tthtsv.ueh.edu.vn )
ii. # 2 Chọn chức năng Tư vấn cá nhân
iii. # 3  Zoom in 150%: Vẫn hiển thị bình thường
iv. # 4 Zoom in 175%:  Các chức năng biến mất
![screenshot10](https://user-images.githubusercontent.com/73493671/99295093-8d31c300-2877-11eb-9a1c-81cc90009445.png)

**Comment by hungho66** [comment]
lỗi responsive chỉ tính ở các kích thước tiêu chuẩn nhé !
VD : Màn hình desktop 100%, Tablet 100%, mobile 100%,....
@31181024020
