### ISSUE TITLE
[Nhóm#4] Lỗi chức năng tìm kiếm ở trang http://handbook.ueh.edu.vn/#/

### ISSUE THREAD

**Issue by 31181023055** [UEHMonQAQC/ST_K44#204]
a. Trình duyệt web: Google Chrome 10 / 8.1 / 8/7 64 bit.
b. Kết quả thực tế: Chức năng tìm kiếm không hoạt động, không sử dụng được
c. Kết quả mong muốn: Chức năng tìm kiếm hoạt động bình thường
d. Các bước để phát hiện lỗi:
i. # 1 Truy cập vào trang web http://handbook.ueh.edu.vn/#/
ii. # 2 Tại thanh tìm kiếm nhập"ktx ueh"
iii. # 3 Nhấp Enter
iv.# 4 Kết quả không đưa đến mục KTX UEH mà vẫn ở trang cũ

<img width="961" alt="Lỗi chức năng tìm kiếm" src="https://user-images.githubusercontent.com/73510833/99342287-24ba0480-28be-11eb-8a6b-672d6b013e8c.png">

**Comment by hungho66** [comment]
Lỗi trùng 
@31181023055 
#129
