### ISSUE TITLE
[Nhóm#06] Lỗi phi chức năng - Lỗi về khả năng tiếp cận - ở trang http://online.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#210]
a.	Web Browser: Google Chrome 86.0.4240.183
b.	Kết quả thực tế: Có tổng cộng 49 lỗi, vi phạm section 508 
Section 508 đã được ban hành để loại bỏ các rào cản trong công nghệ thông tin, để tạo ra các cơ hội mới cho người khuyết tật, và khuyến khích phát triển các công nghệ sẽ giúp đạt được những mục tiêu này.
![image](https://user-images.githubusercontent.com/73525127/99366532-54333600-28eb-11eb-9c37-c27c1fdf9944.png)
c.	Kết quả mong đợi: Không phát hiện lỗi
d.	Các bước phát hiện lỗi:
i. #1: Truy cập vào trang http://www.cynthiasays.com/
![image](https://user-images.githubusercontent.com/73525127/99366594-67460600-28eb-11eb-93a9-ab9092768d5f.png)
ii. #2: Điền vào địa chỉ email
![image](https://user-images.githubusercontent.com/73525127/99366622-6f9e4100-28eb-11eb-856c-d506d1411ecf.png)
iii. #3: Nhập vào text box đường link http://online.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/73525127/99366658-7cbb3000-28eb-11eb-940f-1f101192a2d8.png)
iv. #4: Chọn chế độ tuân thủ là Section 508 (Trang web có thể sử dụng được bởi những người khuyết tật như thính giác, mù màu, tuổi già và các nhóm thiệt thòi khác)
![image](https://user-images.githubusercontent.com/73525127/99366684-847ad480-28eb-11eb-9dcf-f10583bf6c81.png)
v. #5: Nhấn chọn check box " I agree to the Terms & Conditions. You must agree to the Terms & Conditions"
![image](https://user-images.githubusercontent.com/73525127/99366698-8ba1e280-28eb-11eb-8fe9-a7245cd9f2eb.png)
vi. #6: Nhấn vào button "Check your site"
![image](https://user-images.githubusercontent.com/73525127/99366720-93fa1d80-28eb-11eb-9e1d-e9a2903f84e2.png)

**Comment by baolong0** [comment]
Mỗi nhóm chỉ được chấp nhận 01 lỗi phi chức năng test bằng TOOL ! 
Nhóm 06 đã được xác nhận lỗi PHI CHỨC NĂNG test bằng tool nên lỗi này không được chấp nhận ! 
@31181025700

**Comment by baolong0** [comment]
Sau khi xác minh lại thì QA chấp nhận lỗi này của nhóm là Lỗi về khả năng tiếp cận.

**Comment by baolong0** [comment]
Việc hội ý giữa các QA , để đảm bảo tính công bằng giữa các nhóm QC, lỗi này sẽ không được tính !!
