### ISSUE TITLE
[Nhóm#10] Lỗi phi chức năng - Hiệu suất load trang chậm không đạt yêu cầu - ở trang https://tuyensinh.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#212]
a. broswer : Opera LVL 2 (core: 71.0.3770.310)
b. Kết quả thực tế: Hiệu suất trả về 64% trên máy tính để bàn, nằm trong khoảng vàng (50-89) nên không đạt
![image](https://user-images.githubusercontent.com/73520248/99376215-3966be80-28f7-11eb-996a-7120b9018725.png)
c. Kết quả mong đợi: 
Trả về kết quả nằm trong khoảng xanh( 90-100)
d.Các bước phát hiện lỗi:
i. #1: Đăng nhập trang https://developers.google.com/speed/pagespeed/insights/
ii. #2:  Nhập link https://tuyensinh.ueh.edu.vn/ vào thanh phân tích chọn phân tích
![image](https://user-images.githubusercontent.com/73520248/99376306-57ccba00-28f7-11eb-8000-17e608d6bb68.png)
iii. #3: Đợi tool check, bấm chọn “Máy tính để bàn” để xem kết quả.
![image](https://user-images.githubusercontent.com/73520248/99376241-44215380-28f7-11eb-9ae7-197798d195e3.png)

**Comment by uyenxinhdep** [comment]
Nhóm chú ý, mỗi nhóm chỉ được tính 1 lần cho lỗi hiệu suất load trang.
Mình đã xác nhận lỗi https://github.com/UEHMonQAQC/ST_K44/issues/206 cho nhóm,
vì vậy lỗi này không được tính, nhóm tìm lỗi khác giúp mình @31181020674
