### ISSUE TITLE
[nhóm#05] - Lỗi phi chức năng – Độ bảo mật trang web - ở trang http://bit.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024008** [UEHMonQAQC/ST_K44#213]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: Trang web ở mức độ bảo mật kém
c. Kết quả mong đợi: Trang sẽ ở mức độ bảo mật tốt
d. các bước phát hiện lỗi.
i. #1 truy cập trang web https://www.immuniweb.com/
ii. #2 Vào mục community edition-> web security test
![8](https://user-images.githubusercontent.com/73530783/99395425-f9add000-2912-11eb-89c5-6500c591b173.jpg)
iii. #3 Nhập link cần test vào 
![9](https://user-images.githubusercontent.com/73530783/99395604-41ccf280-2913-11eb-811d-1ce20f11c291.jpg)
iv. #4 Độ bảo mật trang web kém ở mức F
![11](https://user-images.githubusercontent.com/73530783/99395812-8eb0c900-2913-11eb-8721-c3f48f1f822c.jpg)

**Comment by baolong0** [comment]
Mỗi nhóm chỉ được chấp nhận 01 lỗi phi chức năng test bằng TOOL ! 
Nhóm 05 đã được xác nhận lỗi PHI CHỨC NĂNG test bằng tool nên lỗi này không được chấp nhận !
@31181024008
