### ISSUE TITLE
[Nhóm #04] - Lỗi chức năng trang UEH Giftshop khi nhấn vào tiêu đề - trang www.tthtsv.ueh.edu.vn

### ISSUE THREAD

**Issue by 31181024185** [UEHMonQAQC/ST_K44#220]
a. Web Browser: Google Chrome phiên bản 86.0.4240.193 (Phiên bản Chính thức) (64 bit)
b. Kết quả thực tế: Khi nhấn vào tiêu đề thì quay lại đầu trang có chứa tiêu đề
![screenshot12](https://user-images.githubusercontent.com/73493671/99404570-5c589900-291e-11eb-9993-7f6f13f30bda.png)

c. Kết quả mong muốn: Khi nhấn vào tiêu đề thì đưa ra Tab mới là Website hay Fanpage của tiêu đề
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang Hỗ trợ sinh viên (www.tthtsv.ueh.edu.vn)
ii. #2 Chọn chức năng Giới thiệu (https://tthtsv.ueh.edu.vn/phong-cham-soc-ho-tro-nguoi-hoc)
iii. #3 Kéo xuống tới phần Liên kết Web (Nằm bên trái trang)
iv. #4 Nhấn chọn tiêu đề UEH Giftshop
[Nhom #04] - Lỗi chức năng hiện thị trang UEH Café khi nhấn vào tiêu đề

**Comment by hungho66** [comment]
Lỗi trùng
@31181024020 
#71
