### ISSUE TITLE
[Nhóm #04] - Lỗi chức năng tự động thoát đăng nhập trang http://www.online.ueh.edu.vn/

### ISSUE THREAD

**Issue by ghost** [UEHMonQAQC/ST_K44#221]
a. Web Browser: CocCoc Phiên bản 90.0.148
b. Kết quả thực tế: Khi nhấn các option trên thanh menu trang http://www.online.ueh.edu.vn/  đều bị tự động thoát đăng nhập ra ngoài
c. Kết quả mong muốn: Khi nhấn các option trên thanh menu trang http://www.online.ueh.edu.vn/ sẽ không bị thoát tài khoản đang được đăng nhập ra.
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang http://www.online.ueh.edu.vn/
![Annotation 2020-11-17 215755](https://user-images.githubusercontent.com/73508317/99405992-f66d1100-291f-11eb-9517-d924e6cc358e.png)
ii. #2 chọn 1 mục nào đó trên thanh menu của trang (ví dụ như trang Trang Chủ)
![Annotation 2020-11-17 215827](https://user-images.githubusercontent.com/73508317/99406207-359b6200-2920-11eb-8bc6-910ac3a3abd2.png)
iii. #3 Bị out tài khoản và bắt phải đăng nhập lần nữa khi bạn muốn quay lại
![Annotation 2020-11-17 220032](https://user-images.githubusercontent.com/73508317/99406601-a80c4200-2920-11eb-8b65-2870b3641910.png)

**Comment by hungho66** [comment]
Lỗi trùng 
@31181024020 
#82
