### ISSUE TITLE
[Nhóm #03] – Lỗi phi chức năng - Phiên bản phần mềm Drupal lỗi thời dẫn đến bảo mật kém - ở trang https://lib.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#225]
a. Web Browser: Microsoft Edge (86.0.622.63)
b. Kết quả thực tế: Phiên bản phần mềm lỗi thời dẫn đến bảo mật kém
![a](https://user-images.githubusercontent.com/73529771/99411941-c2491e80-2926-11eb-9211-98c0319803ab.png)
c. Kết quả mong đợi: Nâng cấp phiên bản Drupal lên phiên bản mới nhất để đảm bảo tính bảo mật
d. Các bước phát hiện lỗi: 
i. #1: Truy cập trang web https://sitecheck.sucuri.net/results/
ii. #2: Điền link https://lib.ueh.edu.vn/ vào ô check
![a](https://user-images.githubusercontent.com/73529771/99412697-9a0def80-2927-11eb-918b-38c0e9ec9ff0.png)
iii. #3: Nhấm button Scan Website và nhận kết quả test
![a](https://user-images.githubusercontent.com/73529771/99413181-17d1fb00-2928-11eb-8d81-1498e9b77894.png)

**Comment by hungho66** [comment]
Đã xác nhận lỗi
