### ISSUE TITLE
[nhóm#09] - lỗi chức năng - link liên kết không truy cập được - ở trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#226]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế:
![dd](https://user-images.githubusercontent.com/73509326/99413602-8911ae00-2928-11eb-9a17-c98fc1faba46.PNG)
c. kết quả mong đợi: link liên kết hoạt động được.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web http://online.ueh.edu.vn/ và click vào button đăng nhập.
![ssss](https://user-images.githubusercontent.com/73509326/99413877-ce35e000-2928-11eb-9a33-ce1caced6b1d.PNG)
ii. #2 nhập thông tin đăng nhập và click đăng nhập.
![zz](https://user-images.githubusercontent.com/73509326/99414003-f4f41680-2928-11eb-8298-d576c84d96f6.PNG)
iii. #3 click vào mục "thời khoá biểu và lịch thi"
![ccdd](https://user-images.githubusercontent.com/73509326/99414245-35539480-2929-11eb-9406-817b045e42c3.PNG)
iv. click vào icon kính lúp trên cùng.
![ff](https://user-images.githubusercontent.com/73509326/99414409-5caa6180-2929-11eb-8ac4-b77b0d132e38.PNG)

**Comment by uyenxinhdep** [comment]
Lỗi bị trùng.
https://github.com/UEHMonQAQC/K40/issues/5
Nhóm tìm lỗi khác giúp mình @31181025359
