### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - load trang chậm  -ở trang https://lms.ueh.edu.vn/my/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#228]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: load trang quá 3s
![ee](https://user-images.githubusercontent.com/73509326/99419631-e577cc00-292e-11eb-852f-aaf73a5eda88.PNG)
c. kết quả mong đợi: load trang nhanh hơn.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web https://gtmetrix.com/
ii. #2 copy paste link https://lms.ueh.edu.vn/my/ vào ô test và click "test your site"
![hhhh](https://user-images.githubusercontent.com/73509326/99420276-9da57480-292f-11eb-9e78-35570f2c21d6.PNG)

**Comment by uyenxinhdep** [comment]
Lỗi bị trùng https://github.com/UEHMonQAQC/ST_K44/issues/135
Nhóm tìm lỗi khác giúp mình @31181025359
