### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - độ bảo mật kém - ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#229]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: Trang web ở mức độ bảo mật kém ở mức C
![llll](https://user-images.githubusercontent.com/73509326/99476240-c0ad4400-2982-11eb-8688-b699f9f9c7b2.PNG)
c. Kết quả mong đợi: Trang sẽ ở mức độ bảo mật tốt hơn cụ thể ở mức B hoặc A
d. các bước phát hiện lỗi.
i. #1 truy cập trang web https://www.immuniweb.com/
ii. #2 Vào mục community edition chọn web security test
![bb](https://user-images.githubusercontent.com/73509326/99423978-b9ab1500-2933-11eb-95ee-55cf564ae93b.PNG)
iii. #3 paste link http://daotao.ueh.edu.vn/ vào phần kiểm tra link và click dấu mũi tên kế bên.
![sss](https://user-images.githubusercontent.com/73509326/99424107-e52dff80-2933-11eb-83f7-bb3cdee780f4.PNG)
iv. #4 độ bảo mật hiển thị ở mức C
![llll](https://user-images.githubusercontent.com/73509326/99476210-b428eb80-2982-11eb-9442-c5cc41291705.PNG)

**Comment by uyenxinhdep** [comment]
Nhóm chú ý, bảo mật kém được chấp nhận khi các bạn lấy được thông tin, xem thông tin riêng tư,...
Nên mình không xác nhận đây là lỗi bảo mật nhé.
Nhóm tìm lỗi khác giúp mình @31181025359
