### ISSUE TITLE
[Nhóm#10] Lỗi phi chức năng - Tốc độ trang web trên thiết bị di động trên mạng 3G - Ở trang https://tuyensinh.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#232]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Kết quả trả về là 3,3 giây nằm trong khoảng cần cải thiện (2,5 – 4 giây)
<img width="468" alt="image" src="https://user-images.githubusercontent.com/73520248/99470264-08c66980-2977-11eb-8049-e1011cdf3c95.png">
c. Kết quả mong đợi: Kết quả trả về nằm trong khoảng (0 – 2,5 giây)
d. Các bước để phát hiện lỗi:
i.#1: Truy cập trang https://www.thinkwithgoogle.com/intl/en-gb/feature/testmysite/
<img width="468" alt="image" src="https://user-images.githubusercontent.com/73520248/99470291-124fd180-2977-11eb-9266-7bd8e17b16fb.png">
ii.#2: Nhập URL trang cần phân tích: https://tuyensinh.ueh.edu.vn/
<img width="468" alt="image" src="https://user-images.githubusercontent.com/73520248/99470306-17148580-2977-11eb-8e85-2eb52303c218.png">
iii.#3: Chọn các mục như trong hình
<img width="468" alt="image" src="https://user-images.githubusercontent.com/73520248/99470313-1bd93980-2977-11eb-8b76-12fe2963c2e6.png">
iv.#4: Kết quả
<img width="468" alt="image" src="https://user-images.githubusercontent.com/73520248/99470321-2267b100-2977-11eb-944d-667d12858b50.png">

**Comment by uyenxinhdep** [comment]
Nhóm chú ý, mình đã nhắc mỗi nhóm chỉ được chấp nhận 1 lỗi về hiệu suất khi test trên công cụ.
Vì vậy lỗi này không được chấp nhận nhé.
Nhóm tìm lỗi khác giúp mình @31181020674
