### ISSUE TITLE
[Nhóm#10] Lỗi chức năng - Lỗi button không hoạt động - ở trang http://se.ueh.edu.vn/vi/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#234]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Button không hoạt động trên nền tảng máy tính
<img width="1131" alt="Screen Shot 2020-11-18 at 08 26 43" src="https://user-images.githubusercontent.com/73520248/99470841-031d5380-2978-11eb-8dbc-7accf58db877.png">
c. Kết quả mong đợi: Button hoạt động hoặc dấu đi trên nền tảng máy tính
d. Các bước phát hiện lỗi
 i. #1 Đăng nhập vào trang  https://se.ueh.edu.vn/vi/
![image](https://user-images.githubusercontent.com/73520248/98354441-4f50c580-2053-11eb-8cee-6f4e4a4094ed.png)
ii. #2 Kéo xuống dưới cùng trang web 
![image](https://user-images.githubusercontent.com/73520248/98354472-58419700-2053-11eb-8cb3-3f8c084bb2d4.png)
iii. #3 Ở góc phải 
<img width="1131" alt="Screen Shot 2020-11-18 at 08 26 43" src="https://user-images.githubusercontent.com/73520248/99470841-031d5380-2978-11eb-8dbc-7accf58db877.png">

**Comment by uyenxinhdep** [comment]
Lỗi bị trùng https://github.com/UEHMonQAQC/K42/issues/245
Nhóm tìm lỗi khác giúp mình @31181020674
