### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - load trang chậm -ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#242]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: load trang quá 5s.
![ww](https://user-images.githubusercontent.com/73509326/99562086-45877480-29fa-11eb-95fc-df3f10bbbbb6.PNG)
c. kết quả mong đợi: load trang nhanh hơn.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web https://gtmetrix.com/
ii. #2 copy paste link http://daotao.ueh.edu.vn/ vào ô test và click "test your site".
![vv](https://user-images.githubusercontent.com/73509326/99562592-e1b17b80-29fa-11eb-9dc7-c28f5e290214.PNG)

**Comment by uyenxinhdep** [comment]
Nhóm xem lại giúp mình, bên trên ghi trang ctct mà bên dưới lại test trang daotao @31181025359

**Comment by uyenxinhdep** [comment]
@31181025359 Sau khi sửa vẫn bị lỗi như đã nói.
Về hiệu suất tải trang http://ctct.ueh.edu.vn/ đã có nhóm thực hiện nên nhóm tìm trang khác giúp mình.
