### ISSUE TITLE
[Nhóm #04] Lỗi phi chức năng - Lỗi bảo mật trang Ký túc xá ở trang https://tthtsv.ueh.edu.vn/dang-ky-noi-tru-ktx-nha-khach.html

### ISSUE THREAD

**Issue by 31181024185** [UEHMonQAQC/ST_K44#245]
a. Web Browser: Google Chrome phiên bản 86.0.4240.198 (Phiên bản Chính thức) (64 bit)
b. Kết quả thực tế: Hiển thị tài khoản và mật khẩu đăng nhập
![2020-11-19 (6)](https://user-images.githubusercontent.com/73493671/99571544-03fcc680-2a06-11eb-88fd-98dab9d44723.png)
c. Kết quả mong muốn: Sử dụng Tài khoản sinh viên do nhà trường đã cấp
d. Các bước phát hiện lỗi:
i. #1 Truy cập trang Hỗ trợ sinh viên (www.tthtsv.ueh.edu.vn)
ii. #2 Kéo xuống phần Tiện ích chọn Đăng ký KTX
iii. #3 Hiện thị trang Đăng ký KTX (https://tthtsv.ueh.edu.vn/dang-ky-noi-tru-ktx-nha-khach.html)
![2020-11-19 (6)](https://user-images.githubusercontent.com/73493671/99571544-03fcc680-2a06-11eb-88fd-98dab9d44723.png)

**Comment by hungho66** [comment]
Không phải lỗi
