### ISSUE TITLE
[Nhóm #03] – Lỗi chức năng – Lỗi chức năng chuyển đổi ngôn ngữ – ở trang https://kqm.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#252]
a. Web Browser: Microsoft Edge. Phiên bản 86.0.622.69 
b. Kết quả thực tế: Ngôn ngữ trang web không chuyển toàn bộ sang ngôn ngữ “English” khi dùng chức năng chuyển đổi ngôn ngữ
![image](https://user-images.githubusercontent.com/73529771/99619916-0c312200-2a57-11eb-85eb-1bc5b49ee47c.png)
c. Kết quả mong đợi: Toàn bộ trang web chuyển sang ngôn ngữ “English”
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://kqm.ueh.edu.vn/ 
ii. #2: Chọn chức năng “English” ở góc phải màn hình
![image](https://user-images.githubusercontent.com/73529771/99619930-118e6c80-2a57-11eb-9ed1-d883b1778bdc.png)

**Comment by hungho66** [comment]
Bị trùng lỗi
@31181023031 
#162
