### ISSUE TITLE
[Nhóm#06] - Lỗi phi chức năng – Trang Sổ tay sinh viên bảo mật trung bình- ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181021429** [UEHMonQAQC/ST_K44#255]
a. Web Browser: Cốc Cốc  90.0.148 
b. Kết quả thực tế: trang Số tay sinh viên bảo mật Trung bình
![125533110_127650042209670_8314362883015711535_n](https://user-images.githubusercontent.com/73511027/99623945-cb89d680-2a5f-11eb-85a2-19dc0baeb60d.png)
c. Kết quả mong đợi: Trang Sổ tay sinh viên được bảo mật cao
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://sitecheck.sucuri.net/
ii. #2: Nhập đường link http://handbook.ueh.edu.vn/#/ và bấm Scan website
![125464919_800204560769408_6455680581265096488_n](https://user-images.githubusercontent.com/73511027/99623923-bca32400-2a5f-11eb-854f-825ef58bd491.png)
iii. #3: Đợi tool check và xem kết quả
![125533110_127650042209670_8314362883015711535_n](https://user-images.githubusercontent.com/73511027/99623945-cb89d680-2a5f-11eb-85a2-19dc0baeb60d.png)

**Comment by baolong0** [comment]
Mỗi nhóm chỉ được chấp nhận 01 lỗi phi chức năng test bằng TOOL ! 
Nhóm 06 đã được xác nhận lỗi PHI CHỨC NĂNG test bằng tool nên lỗi này không được chấp nhận !

**Comment by baolong0** [comment]
@31181021429
