### ISSUE TITLE
[nhóm#09] - lỗi chức năng - lỗi tìm kiếm - ở trang https://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#260]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: tìm ký tự sai  ('-) mà vẫn trả về thông báo có kết quả.
![ee](https://user-images.githubusercontent.com/73509326/99643514-5b8b4880-2a7f-11eb-9af5-d18103f52fc1.PNG)
c. kết quả mong đợi: không trả về kêt quả khi tù khoá tìm kiếm sai.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web [https://lms.ueh.edu.vn/](https://lms.ueh.edu.vn/) và đăng nhập bằng tài khoản sinh viên.
![hhhh](https://user-images.githubusercontent.com/73509326/99643017-c5572280-2a7e-11eb-9238-f05555c6641f.PNG)
ii. #2 lick vô mục tìm kiếm và gõ ký từ dấu nháy trên và dấu gạch ngang ('-).
![ggg](https://user-images.githubusercontent.com/73509326/99643453-46aeb500-2a7f-11eb-94d6-850416d83557.PNG)
iii. #3 ấn enter sẽ thấy trả về kết quả nhu hình.
![ee](https://user-images.githubusercontent.com/73509326/99643531-62b25680-2a7f-11eb-85b8-18fe6a70ab4f.PNG)

**Comment by uyenxinhdep** [comment]
Đây là chức năng tìm kiếm theo thứ tự đặc biệt của hệ thống.
Không phải lỗi chức năng, nhóm tìm lỗi khác giúp mình @31181025359
