### ISSUE TITLE
[nhóm#09] - lỗi chức năng - button không hoạt động - ở trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#261]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: không click chọn được button.
![gàasfasf](https://user-images.githubusercontent.com/73509326/99644714-d99c1f00-2a80-11eb-90cb-8d4ba1936d8f.PNG)
c. kết quả mong đợi: button có thể hoạt động được.
d. các bước phát hiện lỗi.
i. #1 truy cập vào trang web [http://online.ueh.edu.vn/](http://online.ueh.edu.vn/) và click đăng nhập.
![qqqq](https://user-images.githubusercontent.com/73509326/99644952-2a137c80-2a81-11eb-9a64-429589895316.PNG)
ii. #2 nhập thông tin tài khoảng và mật khẩu -> click button nhớ mật khẩu.
![bbbbb](https://user-images.githubusercontent.com/73509326/99645106-5f1fcf00-2a81-11eb-946e-5da65d8e574f.PNG)

**Comment by uyenxinhdep** [comment]
Lỗi bị trùng https://github.com/UEHMonQAQC/ST_K44/issues/35 
Nhóm tìm lỗi khác giúp mình @31181025359
