### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - tự động load lại trang khi thực hiện chức năng - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#263]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: nhập từ khoá "select" vào ô mssv và click tìm kiếm thì trang tự load lại, không thông báo kết quả.
![ssssssssss](https://user-images.githubusercontent.com/73509326/99647923-ffc3be00-2a84-11eb-918e-d652c3330012.PNG)
c. kết quả mong đợi: thông báo mssv sai và yêu cầu nhập lại.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web [http://ctct.ueh.edu.vn/](http://ctct.ueh.edu.vn/)
ii. #2 kéo xuống phần "tra cứu cộng, trừ điểm rèn luyện" và nhập từ khoá "select".
![aaaaa](https://user-images.githubusercontent.com/73509326/99648384-91cbc680-2a85-11eb-93ec-5b4e6103744a.PNG)
iii. #3 click tìm kiếm trang sẽ tự động load lại và không thông báo lỗi.

**Comment by uyenxinhdep** [comment]
Giống lỗi https://github.com/UEHMonQAQC/ST_K44/issues/262 
Nhóm tìm lỗi khác giúp mình @31181025359
