### ISSUE TITLE
[Nhóm#07] - Lỗi phi chức năng – Độ bảo mật trang web - ở trang https://vieclam.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181022249** [UEHMonQAQC/ST_K44#271]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: Trang web ở mức độ bảo mật kém
c. Kết quả mong đợi: Trang sẽ ở mức độ bảo mật tốt
d. Các bước phát hiện lỗi.
i. Truy cập trang web https://www.immuniweb.com/
ii. Vào mục Community edition-> Web security test
![image](https://user-images.githubusercontent.com/73516822/99682961-657a6f00-2ab2-11eb-90d3-8b0f253ead0c.png)
iii. Nhập https://vieclam.ueh.edu.vn/ và ô và tiến hành test
iv. Độ bảo mật trang web kém ở mức C
![image](https://user-images.githubusercontent.com/73516822/99683316-c9049c80-2ab2-11eb-9029-22060d44d575.png)

**Comment by PhucLuan** [comment]
@31181022249 Đối với lỗi bảo mật, mình cần hack được, làm lộ thông tin mà người ta không muốn cho mình xem, hoặc các trường hợp khác của lỗi bảo mật các bạn có thể google để tìm hiểu thêm. Trường hợp này tạm thời mình không xác nhận đây là lỗi và sẽ hỏi lại thầy sau nhé.
