### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - không trả form thông báo - ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#272]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: khi click "gửi" thì trang web tự load lại và không trả kết quả thông báo gửi.
![qqq](https://user-images.githubusercontent.com/73509326/99692264-b42d0680-2abc-11eb-910b-fc96b2d8a796.PNG)
c. kết quả mong đợi: thông báo kết quả khi thực hiện chức năng "gửi" thông tin và không tự động load lại trang.
d. các bước phát hiện lỗi.
i. truy cập trang web [http://daotao.ueh.edu.vn/](http://daotao.ueh.edu.vn/ )
![zzz](https://user-images.githubusercontent.com/73509326/99692609-1423ad00-2abd-11eb-9fba-9740c132ebd3.PNG)
ii. #2 click chọn "liên hệ"
![hhh](https://user-images.githubusercontent.com/73509326/99692816-4cc38680-2abd-11eb-80d4-26008895dfa2.PNG)
iii. #3 nhập đầy đủ thông tin vào các trường trong "liên hệ" và click "gửi"
![qqq](https://user-images.githubusercontent.com/73509326/99693091-92804f00-2abd-11eb-92d2-32623a0ea796.PNG)

**Comment by uyenxinhdep** [comment]
Giống lỗi https://github.com/UEHMonQAQC/K42/issues/220
Nhóm tìm lỗi khác giúp mình @31181025359
