### ISSUE TITLE
[nhóm#09] - lỗi chức năng - lỗi checkbox - ở trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#281]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: checkbox click chọn không được. khi sửa HTML thì chọn được
![rrr](https://user-images.githubusercontent.com/73509326/99751980-f7679380-2b15-11eb-8fa9-18edbf728db5.PNG)
c. kết quả mong đợi: click chọn được checkbox.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web [http://online.ueh.edu.vn/](http://online.ueh.edu.vn/) và click button đăng nhập.
![jjj](https://user-images.githubusercontent.com/73509326/99752081-3c8bc580-2b16-11eb-9585-2e964fdd40a5.PNG)
ii. #2 click chuột phải lên dòng "ghi nhớ..." và chọn kiểm tra.
![ttt](https://user-images.githubusercontent.com/73509326/99752298-a1472000-2b16-11eb-8425-94a875916286.PNG)
iii. #3 nhấn double chọn "disabled="disabled" và xoá.
![nnn](https://user-images.githubusercontent.com/73509326/99752568-27fbfd00-2b17-11eb-8776-73f17b9b24ec.PNG)
iv. #4 checkbox đã thực hiện được.
![lll](https://user-images.githubusercontent.com/73509326/99752698-609bd680-2b17-11eb-8dcf-6826f3a5fd3e.PNG)

**Comment by uyenxinhdep** [comment]
Sau khi thực hiện các bước, trang không đăng xuất tài khoản được.
Đây thuộc lỗi chức năng @31181025359 (mô tả rõ các bước sau đó)
