### ISSUE TITLE
[Nhóm #03] – Phi chức năng – Tốc độ LCP chậm – ở trang http://comm.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#282]
a.	Web browers: Opera version 15.0
b.	Kết quả thực tế: Tốc độ LCP đạt 3.8s
![image](https://user-images.githubusercontent.com/73529771/99766474-c302d000-2b33-11eb-8084-be758e32a2bb.png) 
c.	Kết quả mong đợi: Tốc độ LCP tầm 1-2s
d.	Các bước để phát hiện lỗi:
     i.	#1: truy cập trang web http://comm.ueh.edu.vn/  --> F12 --> Lighthouse
![image](https://user-images.githubusercontent.com/73529771/99766743-491f1680-2b34-11eb-9043-6510029f60b3.png)
    ii.	#2: Chọn Performance --> Generate Report
![image](https://user-images.githubusercontent.com/73529771/99766971-c8ace580-2b34-11eb-8ba7-399505f91196.png)
*So sánh kết quả cho thấy tốc độ LCP chậm so với mức độ chung

**Comment by hungho66** [comment]
Đã xác nhận lỗi

**Comment by hungho66** [comment]
Lỗi bị trùng (Dùng tool)
