### ISSUE TITLE
[Nhóm #03] – Lỗi phi chức năng – Speed index trang web chậm – ở trang https://lib.ueh.edu.vn/en

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#283]
a. Web browers: Microsoft Edge Phiên bản 86.0.622.69 (Bản xây dựng chính thức) (64-bit)
b. Kết quả thực tế: Tốc độ hiển thị nội dung trang web chậm 
![vbnm](https://user-images.githubusercontent.com/73529771/99791662-82697d80-2b58-11eb-8eef-412b5746be35.png)
c. Kết quả mong đợi: Tốc độ hiển thị trong khoảng tầm 1,250 mili - 2 giây 
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://lib.ueh.edu.vn/en
ii. #2: F12 -> Chọn "Lighthouse"
![ưẻ](https://user-images.githubusercontent.com/73529771/99793260-f9077a80-2b5a-11eb-93d6-84ff00c6eca8.png)
iii. #3: Ở "Categories" chọn "Performance" và Device chọn "Desktop"
![vbnm,gn](https://user-images.githubusercontent.com/73529771/99794582-f27a0280-2b5c-11eb-8aa3-2825cbeec0f7.png)
iiii. #4: Chọn "Generate Report"
![nm,](https://user-images.githubusercontent.com/73529771/99793989-12f58d00-2b5c-11eb-8827-e10c07d04b98.png)
*Tốc độ load trang luôn chậm hơn tốc độ lý tưởng rất nhiều
(theo : https://bizflycloud.vn/tin-tuc/nhung-dieu-can-biet-ve-website-speed-test-va-so-sanh-mot-so-cong-cu-website-speed-test-pho-bien-20180918102314867.htm#:~:text=Speed%20Index%3A%20Cho%20bi%E1%BA%BFt%20t%E1%BB%91c,l%C3%A0%20d%C6%B0%E1%BB%9Bi%201%2C250%20mili%20gi%C3%A2y.&text=N%E1%BA%BFu%20%C4%91%E1%BB%99%20tr%E1%BB%85%20l%E1%BB%9Bn%20h%C6%A1n,%E1%BB%A9ng%20d%E1%BB%A5ng%20b%E1%BB%8B%20lag%2C%20ch%E1%BA%ADm. )

**Comment by hungho66** [comment]
Dùng Tool nhiều --> Lỗi trùng
