### ISSUE TITLE
[Nhóm#06] - Lỗi phi chức năng – Gía trị LCP không đạt yêu cầu (7.8s thay vì là dưới 2.5s) - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#289]
a.	Web Browser: Google Chrome 87.0.4280.66
b.	Kết quả thực tế: Gía trị LCP không đạt yêu cầu (7.8s thay vì là dưới 2.5s) 
![image](https://user-images.githubusercontent.com/73525127/99811595-f5ceb780-2b77-11eb-8d95-6df481d7d950.png)
c.	Kết quả mong đợi: Gía trị LCP bé hơn hoặc bằng 2.5s
d.	Các bước phát hiện lỗi:
i.	#1: Truy cập vào trang http://ctct.ueh.edu.vn/
ii.	#2: Nhấn phím F12 
iii.	#3: Nhấn vào mũi tên đôi và chọn mục Lighthouse
![image](https://user-images.githubusercontent.com/73525127/99811621-fcf5c580-2b77-11eb-8275-00ff487f8562.png)
iv.	#4: Nhấn vào button “Generate report” để bắt đầu test
![image](https://user-images.githubusercontent.com/73525127/99811641-041cd380-2b78-11eb-8512-ec16cd70567f.png)
v.	#5: Xem kết quả Largest Contentful Paint hiển thị

**Comment by baolong0** [comment]
Mỗi nhóm chỉ được chấp nhận 01 lỗi phi chức năng test bằng TOOL ! 
Nhóm 06 đã được xác nhận lỗi PHI CHỨC NĂNG test bằng tool nên lỗi này không được chấp nhận ! 
@31181025700
