### ISSUE TITLE
[Nhóm#06] - Lỗi chức năng – Không tương thích thiết bị Mobile khi sử dụng chức năng - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#292]
a.	Web Browser: Google Chrome 87.0.4280.66 cho PC / Google dành cho IOS 14.2
b.	Kết quả thực tế: Không thể sử dụng chức năng “Đóng cửa sổ này” trên mobile như khi dùng trên PC  
![image](https://user-images.githubusercontent.com/73525127/99815684-37ae2c80-2b7d-11eb-8f80-05212af79106.png)
c.	Kết quả mong đợi: có thể sử dụng chức năng “Đóng cửa sổ này” trên mobile
d.	Các bước phát hiện lỗi:
i.	#1: Truy cập vào đường link http://ctct.ueh.edu.vn/ trên cả PC và Mobile để so sánh
ii.	#2: Tại mục Giới thiệu, nhấn chọn Ban lãnh đạo
![image](https://user-images.githubusercontent.com/73525127/99815702-3ed53a80-2b7d-11eb-927d-78c39fa3f1b0.png)
iii.	#3: Kéo xuống hết trang, nhấn vào icon máy in
![image](https://user-images.githubusercontent.com/73525127/99815721-4563b200-2b7d-11eb-9e69-08e5fd5677e6.png)
iv.	#4: Nhấn vào chức năng “Đóng cửa sổ này” trên cả PC và Mobile để so sánh kết quả
![image](https://user-images.githubusercontent.com/73525127/99815739-4bf22980-2b7d-11eb-8be1-b0cc1a7b04b0.png)

**Comment by baolong0** [comment]
Chức năng vẫn hoạt động bình thường thì sao lại là lỗi chức năng? 
Chức năng của nó là ĐÓNG và nó vẫn ĐÓNG bình thường? 
@31181025700
