### ISSUE TITLE
[Nhóm #07] Lỗi phi chức năng - Lỗi khả năng tiếp cận ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024574** [UEHMonQAQC/ST_K44#295]
a. Web Browser: Microsoft Edge Version 87.0.664.41 
b. Kết quả thực tế: Phát hiện được 42 lỗi
![image](https://user-images.githubusercontent.com/73492084/99821174-49df9900-2b84-11eb-8287-625b0339bef5.png)

c. Kết quả mong đợi: Không lỗi nào được tìm thấy
d. Các bước phát hiện lỗi: 
i.#1: Vào trang https://www.webaccessibility.com/
![Screenshot 2020-11-20 230242](https://user-images.githubusercontent.com/73492084/99821546-c5d9e100-2b84-11eb-9d42-d8d82b434007.png)
ii. #2: Nhập vào box link Phòng Đào tạo và submit Test
![image](https://user-images.githubusercontent.com/73492084/99821773-05a0c880-2b85-11eb-9596-b54509eef9ed.png)
![image](https://user-images.githubusercontent.com/73492084/99822034-51537200-2b85-11eb-9583-212bd6e17ab5.png)

**Comment by PhucLuan** [comment]
@31181024574 đây là vi phạm chuẩn code tuy nhiên trang trang vẫn hoạt động bình thường. Do đó đây không phải lỗi. Ví dụ: trang web nhúng js ở trên thẻ head là vi phạm chuẩn, nhưng code vẫn chạy và không có lỗi, thì đây không phải lỗi nhé.
