### ISSUE TITLE
[Nhom#07] Lỗi bảo mật-Ở trang http://khkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024110** [UEHMonQAQC/ST_K44#300]
a.Web Browser: Google Chrome Phiên bản 87.0.4280.66
b.Kết quả thực tế:Mật khẩu không bị ẩn
c.Kết quả mong đợi: Mật khẩu được ẩn
d. Các bước thực hiện lỗi:
i. #1: Vào trang khkt.ueh.edu.vn
ii. #2: Chọn mục tổ chức lịch thi
iii. #3: Chọn phần Đăng ký tham gia coi thi
![Chưa có tên](https://user-images.githubusercontent.com/73484817/99866029-93f66800-2be0-11eb-816f-e32288a29e54.png)
iv. #4: Điền thông tin vào ô “Tên Đăng Nhập ” và “Mật Khẩu” .
![Chưa có tê1n](https://user-images.githubusercontent.com/73484817/99866034-9b1d7600-2be0-11eb-9b77-665816d61191.png)

**Comment by PhucLuan** [comment]
@ 31181024110 đây là do hệ thống không hỗ trợ ẩn mật khẩu. Do đó không phải lỗi bảo mật.
