### ISSUE TITLE
[Nhóm #03] – Lỗi chức năng – Tính khả dụng – ở trang https://lib.ueh.edu.vn

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#305]
a.	Web browers: Opera version 15.0
b.	Kết quả thực tế: Không hiển thị đầy đủ nội dung cũng như chức năng cần thiết khi sử dụng ngôn ngữ Tiếng Việt 
![image](https://user-images.githubusercontent.com/73529771/99937465-618f6b00-2d98-11eb-97dd-6aa6ee038ce5.png)
c.	Kết quả mong đợi: Hiển thị đầy đủ thông tin, chức năng như khi sử dụng ngôn ngữ Tiếng Anh
d.	Các bước để phát hiện lỗi:
      i.	#1: truy cập trang web https://lib.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/73529771/99937575-a87d6080-2d98-11eb-94c5-b2f2af98afd0.png) 
     ii.	#2: Di chuyển chuột tới "PRESS RELEASE" --> "last" --> Click "OCT 18" để chuyển về Tiếng Việt --> Trang chủ
![image](https://user-images.githubusercontent.com/73529771/99938077-aa93ef00-2d99-11eb-9c59-f4f5462682d5.png)
![image](https://user-images.githubusercontent.com/73529771/99938106-b97aa180-2d99-11eb-9bc6-95eb6cdb8bbb.png)
![image](https://user-images.githubusercontent.com/73529771/99938130-c3040980-2d99-11eb-99ca-7495703ce62f.png)
     iii.	#3: Vào "Liên kết nhanh" sau đó so sánh với phiên bản Tiếng Anh
![image](https://user-images.githubusercontent.com/73529771/99938422-563d3f00-2d9a-11eb-9eca-84fb28b09b26.png)
*Lỗi tính khả dụng không hiển thị được hết nội dung và chức năng của trang web khi chuyển sang Tiếng Việt !

**Comment by hungho66** [comment]
@31181023031 Không phải Lỗi  phi chức năng
Lỗi này nhóm khác cũng báo rồi và là lỗi chức năng

**Comment by hungho66** [comment]
@hungho66 
Trùng #264
