### ISSUE TITLE
[Nhóm #03] – Lỗi phi chức năng – Ngôn ngữ không đồng bộ – ở trang https://lib.ueh.edu.vn

### ISSUE THREAD

**Issue by 31181023031** [UEHMonQAQC/ST_K44#306]
Web browers: Opera version 15.0
b.	Kết quả thực tế: Các chức năng hiển thị ngôn ngữ không đồng bộ với nhau
![image](https://user-images.githubusercontent.com/73529771/99945475-4415cd80-2da7-11eb-8fd0-e20a74c186af.png)
c.	Kết quả mong đợi: Hiển thị ngôn ngữ đồng bộ
d.	Các bước để phát hiện lỗi:
      i.	#1: truy cập trang web https://lib.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/73529771/99937575-a87d6080-2d98-11eb-94c5-b2f2af98afd0.png) 
     ii.	#2: Di chuyển chuột tới "PRESS RELEASE" --> "last" --> Click "OCT 18" để chuyển về Tiếng Việt 
![image](https://user-images.githubusercontent.com/73529771/99938077-aa93ef00-2d99-11eb-9c59-f4f5462682d5.png)
![image](https://user-images.githubusercontent.com/73529771/99938106-b97aa180-2d99-11eb-9bc6-95eb6cdb8bbb.png)
     iii.	#3: Về lại Trang chủ
![image](https://user-images.githubusercontent.com/73529771/99945933-19784480-2da8-11eb-8922-d6ff2d62929d.png)

**Comment by hungho66** [comment]
Lỗi trùng 
#264
