### ISSUE TITLE
[Nhóm#08] - Lỗi giao diện - Căn không đều các đối tượng chữ và hình - trang http://nnkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by namnguyenphuong355** [UEHMonQAQC/ST_K44#310]
a. Web Browser: Google Chrome Windows 10

b. Web Browser: Chrome

c. Kết quả thực tế: Căn không đều các đối tượng chữ và hình với nhau, margin top và bottom căn không đều

![2](https://user-images.githubusercontent.com/73516957/99978946-26615c00-2dd9-11eb-98c6-cdcdd465314d.jpg)

![3](https://user-images.githubusercontent.com/73516957/99979022-3d07b300-2dd9-11eb-8d30-fefea3521797.jpg)

d. Kết quả mong muốn: Căn đều các mục trình bày và dãn margin top và bottom phù hợp
e. Các bước để phát hiện lỗi:
i.     #1 Truy cập link: http://nnkt.ueh.edu.vn/index.php/2015/05/31/tu-dien-lingoes-2/
ii.    #2 Kéo xuống gần footer

![4](https://user-images.githubusercontent.com/73516957/99979524-c4552680-2dd9-11eb-89d1-23c6cceb9856.jpg)

**Comment by PhucLuan** [comment]
@31181023044 trang vẫn căn đều nhé, mặc dù một số tin tức không có hình minh họa, tuy nhiên phần nội dung ở từng dòng, cột vẫn thẳng hàng, đều nhau, không bị tràn nội dung sang dòng khác. Do đó không phải lỗi nhé.
