### ISSUE TITLE
[Nhóm#08] - Lỗi giao diện - Logo mất màu trong form đăng nhập ở - trang nnkt.ueh.edu.vn

### ISSUE THREAD

**Issue by namnguyenphuong355** [UEHMonQAQC/ST_K44#317]
a.	Web browser: Google Chrome cho Windows 10
b.	Kết quả thực tế: banner ở trang đăng nhập bị mất màu
![image](https://user-images.githubusercontent.com/73516957/99983311-48a9a880-2dde-11eb-97ed-123878e7cbf3.png)

c.	Kết quả mong muốn: banner màu bình thường
d.	Các bước phát hiện lỗi
i.	#1: Người dùng truy cập trang nnkt.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73516957/99983341-5101e380-2dde-11eb-880c-aa814b55156c.png)

ii.	#2: Người dùng chọn chức năng đăng nhập
![image](https://user-images.githubusercontent.com/73516957/99983368-595a1e80-2dde-11eb-8e7c-df80cbdf68bb.png)

iii.	#3: Người dùng phát hiện lỗi banner bị mất màu
![image](https://user-images.githubusercontent.com/73516957/99983401-6545e080-2dde-11eb-9b82-620204fc4e95.png)

**Comment by PhucLuan** [comment]
@31181023044 trùng với lỗi #178. Lưu ý, các bạn tự check lại trong team của mình, trường hợp issue mới của các bạn bị trùng với chính issue cũ của team mình ở lần thứ 2 sẽ bị trừ điểm nhé.
