### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng - Không có ràng buộc bắt buộc cho trường Email - trang http://nnkt.ueh.edu.vn

### ISSUE THREAD

**Issue by namnguyenphuong355** [UEHMonQAQC/ST_K44#325]
a. Web Browser : Google Chrome Windows 10
b. Kết quả thực tế : trường email không đúng định dạng @gmail 
![image](https://user-images.githubusercontent.com/73516957/100059173-3458c080-2e5d-11eb-8822-ec48236f1b3d.png)

c. Kết quả mong đợi:  Có rằng buộc đúng định dạng của trường Email
d. Các bước phát hiện lỗi:

i.        #1 Truy cập vào trang http://nnkt.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73516957/100059219-489cbd80-2e5d-11eb-9d26-bf5268388d14.png)

ii.       #2 Truy cập phần đăng ký của trang
![image](https://user-images.githubusercontent.com/73516957/100059258-55b9ac80-2e5d-11eb-91de-2d3ea66ec53a.png)

iii.      #3 Phần đăng kí nhập địa chỉ email không đúng dạng vẫn được chấp nhận

![image](https://user-images.githubusercontent.com/73516957/100059296-69fda980-2e5d-11eb-8d33-1ac41657c850.png)

![image](https://user-images.githubusercontent.com/73516957/100059305-6d913080-2e5d-11eb-8a18-f1b26032c65f.png)

**Comment by PhucLuan** [comment]
@31181023044 đây là do trang không hỗ trợ chức năng kiểm tra giá trị truyền vào, chứ không phải lỗi. Tuy nhiên đây là một lỗ hỏng bảo mật, các bạn có thể khai thác để tìm ra lỗi bảo mật, nếu làm được mình sẽ cộng điểm về chất lượng issue nhé, cảm ơn.
