### ISSUE TITLE
[Nhóm#06] - Lỗi phi chức năng – Bảo mật không đạt yêu cầu - ở trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024834** [UEHMonQAQC/ST_K44#329]
a. Web Browser: Cốc Cốc 91.0.144
b. Kết quả thực tế: Bảo mật chỉ ở mức độ trung bình
![PCN1-4](https://user-images.githubusercontent.com/73509553/100071361-89043780-2e6d-11eb-923d-eda0c50eed6c.png)
c. Kết quả mong đợi: Bảo mật ở mức độ cao
d. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang http://online.ueh.edu.vn/
ii. #2:  Coppy đường dẫn http://online.ueh.edu.vn/
![PCN-Online](https://user-images.githubusercontent.com/73509553/100071632-d8e2fe80-2e6d-11eb-915a-8844d3c51bc1.png)
iii. #3: Truy cập vào trang https://sitecheck.sucuri.net/
iv. #4: Pass đường dẫn trang online UEH vào khung dưới đây
v. #5: Bấm Scan Website và xem kết quả
![PCN-Online2](https://user-images.githubusercontent.com/73509553/100071891-2495a800-2e6e-11eb-8bf4-da3634344332.png)

**Comment by baolong0** [comment]
Mỗi nhóm chỉ được chấp nhận 01 lỗi phi chức năng test bằng TOOL ! 
Nhóm 06 đã được xác nhận lỗi PHI CHỨC NĂNG test bằng tool nên lỗi này không được chấp nhận ! 
@31181024834  
@31181021429
