### ISSUE TITLE
[Nhóm#06] - Lỗi phi chức năng – Đường link không hiển thị đang ở trang nào gây khó khăn cho người dùng - http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#356]
a.	Web Browser: Google Chrome 87.0.4280.66 
b.	Kết quả thực tế: Nhấp vào mục chương trình đào tạo nhưng trên đường link vẫn không hiển thị đang ở trang chương trình đào tạo gây khó khăn cho người dùng.
![image](https://user-images.githubusercontent.com/73525127/100567298-bda74180-32fa-11eb-87ed-b57e5a58f5a2.png)
c.	Kết quả mong đợi: Hiển thị online.ueh.edu.vn/chuongtrinhdaotao
d.	Các bước phát hiện lỗi:
i.	#1: Truy cập vào trang http://online.ueh.edu.vn/
ii.	#2: Đăng nhập vào hệ thống
iii.	#3: Nhấn chọn mục “Chương trình đào tạo” 
iv.	#4: Xem đường link hiển thị

**Comment by baolong0** [comment]
Single-page application . Đây là keywork nếu nhóm bạn muốn tìm hiểu !!
