### ISSUE TITLE
[Nhóm#10] Lỗi Phi chức năng – Tính khả dụng (không đồng bộ khi chuyển ngôn ngữ) ở trang https://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#371]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Không đồng bộ khi chuyển ngôn ngữ
![image](https://user-images.githubusercontent.com/73520248/100646164-401e1880-3370-11eb-94be-a849ac9abf13.png)
c. Kết quả mong đợi: Đồng bộ khi chuyển ngôn ngữ
d. Các bước để phát hiện lỗi:
i.#1: Truy cập trang https://lms.ueh.edu.vn/
ii.#2: Chọn ngôn ngữ Tiếng Anh
![image](https://user-images.githubusercontent.com/73520248/100646201-4d3b0780-3370-11eb-9997-cfc074f697f7.png)
iii.#3: Nhận về trang web chưa được đồng bộ sang tiếng Anh
![image](https://user-images.githubusercontent.com/73520248/100646214-51672500-3370-11eb-91d9-0c966c03ab64.png)

**Comment by uyenxinhdep** [comment]
Đây là lỗi chức năng nhé @31181020674 
và mình đã xác nhận lỗi https://github.com/UEHMonQAQC/ST_K44/issues/259 hợp lệ
