### ISSUE TITLE
[Nhóm#10] Lỗi Phi chức năng – Tính khả dụng (mất chức năng khi chuyển ngôn ngữ) ở trang http://ibr.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#372]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Các chức năng hiển thị dropdown "CHƯƠNG TRÌNH LINCOLN" ở hai ngôn ngữ không giống nhau
![image](https://user-images.githubusercontent.com/73520248/100646368-870c0e00-3370-11eb-82a0-211f37d4eafd.png)
c. Kết quả mong đợi: Các chức năng hiển thị dropdown "CHƯƠNG TRÌNH LINCOLN" ở hai ngôn ngữ giống nhau
![image](https://user-images.githubusercontent.com/73520248/100646379-8a06fe80-3370-11eb-8dd6-0e6ecbfe5b0d.png)
d. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://ibr.ueh.edu.vn/
ii.#2: Rê con trỏ chuột vào "CHƯƠNG TRÌNH LINCOLN" và quan sát kết quả
![image](https://user-images.githubusercontent.com/73520248/100646394-8ffcdf80-3370-11eb-8a17-42e42aaf56f9.png)
iii.#3: Chuyển sang ngôn ngữ Tiếng Anh bằng cách click chuột vào biểu tượng trên cùng bên phải trang web như trong hình
![image](https://user-images.githubusercontent.com/73520248/100646413-955a2a00-3370-11eb-9ad9-9c3987f852f7.png)
iv.#4: Rê chuột vào mục “LINCOLN PROGRAM” và xem kết quả
![image](https://user-images.githubusercontent.com/73520248/100646426-98edb100-3370-11eb-96c7-059205764310.png)

**Comment by uyenxinhdep** [comment]
Xác nhận lỗi hợp lệ.

**Comment by uyenxinhdep** [comment]
Sau khi kiểm tra lại mình xác nhận nó thuộc lỗi chức năng @31181020674 
Nhóm sửa lại giúp mình
