### ISSUE TITLE
[Nhóm#10] - Lỗi phi chức năng - lỗi đồng bộ ( nội dung không tương thích khi chuyển ngôn ngữ) - ở trang http://ibr.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#373]
a.	Web Browser : Google Chrome 86.0.4240.198
b.	Kết quả thực tế: Nội dung không tương thích khi chuyển đổi ngôn ngữ
![image](https://user-images.githubusercontent.com/73520248/100646710-f4b83a00-3370-11eb-8674-f5ca5a2c5db3.png)
c.	Kết quả mong đợi: Tương thích khi chuyển đổi ngôn ngữ
![image](https://user-images.githubusercontent.com/73520248/100646736-000b6580-3371-11eb-82b9-b5168e933166.png)
d.	Các bước phát hiện lỗi:
i. #1 Truy cập trang http://ibr.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/73520248/100646798-19141680-3371-11eb-91e8-a3032decf0a7.png)
ii. #2 Check nội dung của trang khi để ngôn ngữ Tiếng Việt
![image](https://user-images.githubusercontent.com/73520248/100646852-30eb9a80-3371-11eb-89d9-08a1785586b9.png)
iii. #3 Chọn thay đổi ngôn ngữ sang tiếng anh hoặc truy cập http://ibr.ueh.edu.vn/home/english
![image](https://user-images.githubusercontent.com/73520248/100646935-4fea2c80-3371-11eb-91a3-cb8141e5a967.png)
iv. #4 Nội dung khi chuyển sang Tiếng Anh ít và không cập nhật nhiều thông tin
![image](https://user-images.githubusercontent.com/73520248/100646710-f4b83a00-3370-11eb-8674-f5ca5a2c5db3.png)

**Comment by uyenxinhdep** [comment]
Lỗi bị trùng https://github.com/UEHMonQAQC/ST_K44/issues/326
Nhóm tìm lỗi khác nhé @31181020674
