### ISSUE TITLE
[Nhóm #10] - Lỗi phi chức năng – thiếu tính chính xác trong chức năng tìm kiếm - Trang http://lms.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#374]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Hiện thị kết quả không liên quan
![image](https://user-images.githubusercontent.com/73520248/100648131-161a2580-3373-11eb-8a44-83e9afa71140.png)
![image](https://user-images.githubusercontent.com/73520248/100648175-28945f00-3373-11eb-925b-06098bab8bbc.png)
c. Kết quả mong đợi: Chỉ hiện thị những kết quả liên quan
d. Các bước phát hiện lỗi:
i. #1 Đăng nhập vào tài khoản lms ở trang http://lms.ueh.edu.vn
![image](https://user-images.githubusercontent.com/73520248/100648438-832dbb00-3373-11eb-90d9-6abee21a8750.png)
ii. #2 ghi a vào mục tìm kiếm ở góc phải trang web và ấn enter để tìm
![image](https://user-images.githubusercontent.com/73520248/100648555-a8222e00-3373-11eb-8592-69fdaab20865.png)
iii. #3 Chọn trang 452 
![image](https://user-images.githubusercontent.com/73520248/100648639-c9831a00-3373-11eb-8c7e-1aee6f1f2c76.png)
iv. #4 kéo xuống gần cuối sẽ thấy bài viết không liên quan tới chữ cái
![image](https://user-images.githubusercontent.com/73520248/100648175-28945f00-3373-11eb-925b-06098bab8bbc.png)

**Comment by uyenxinhdep** [comment]
Đây không phải lỗi phi chức năng @31181020674, trang web sẽ tìm kiếm tất cả các từ khóa liên quan có ở tiêu đề và bên trong nội dung nên mình xác nhận đây không phải lỗi nhé.
