### ISSUE TITLE
[Nhóm#10] - Lỗi phi chức năng - Hình ảnh không load được khi chuyển qua ngôn ngữ Anh - ở trang http://se.ueh.edu.vn/en/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#381]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Hình ảnh của trang khi chuyển ngôn ngữ không load được
![image](https://user-images.githubusercontent.com/73520248/100701045-7049d380-33d1-11eb-912e-548274b838db.png)
c. Kết quả mong đợi: Hình ảnh load được 
d. Các bước để phát hiện lỗi:
i.#1: Truy cập trang http://se.ueh.edu.vn/vi/ và kiểm tra hình ảnh của trang có hoạt động
![image](https://user-images.githubusercontent.com/73520248/100701251-d6cef180-33d1-11eb-9ab3-233ca7626b3f.png)
ii.#2: Thay đổi đường link "vi" thành "en" trên đường dẫn và nhấn enter 
![image](https://user-images.githubusercontent.com/73520248/100701219-c3bc2180-33d1-11eb-8515-ad02665d39d5.png)
iii.#3: kết quả 
![image](https://user-images.githubusercontent.com/73520248/100701045-7049d380-33d1-11eb-912e-548274b838db.png)

**Comment by uyenxinhdep** [comment]
![image](https://user-images.githubusercontent.com/72490393/100706583-d89db280-33db-11eb-8ae0-352d6faa90a0.png)

**Comment by uyenxinhdep** [comment]
thực hiện theo chức năng của trang web hình ảnh vẫn có nhé nên đây không coi là lỗi @31181020674
