### ISSUE TITLE
[nhóm#05] - Lỗi phi chức năng – Tốc độ phản hồi của trang chậm ở giao diện máy tính - ở trang https://payment.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024008** [UEHMonQAQC/ST_K44#383]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: Tốc độ phản hồi trang chậm
![1](https://user-images.githubusercontent.com/73530783/100703213-a5582500-33d5-11eb-92fe-c0447253400b.jpg)
c. Kết quả mong đợi: tốc độ phản hồi trang sẽ nhanh hơn
d. Các bước để phát hiện lỗi:
i. #1: Truy cập vào trang https://developers.google.com/speed/pagespeed/insights/
ii. #2: Nhập địa chỉ của trang https://payment.ueh.edu.vn/
iii. #3: Nhấn chọn nút phân tích

**Comment by baolong0** [comment]
mỗi nhóm chỉ được xác nhận 1 lỗi phi chức năng dùng tool hiệu suất !
