### ISSUE TITLE
[nhóm#02] - lỗi chức năng - lỗi ghi nhận số điện thoại sai - ở trang http://taichuc.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020316** [UEHMonQAQC/ST_K44#39]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: ghi nhận số điện thoại bằng chữ nhưng báo thành công
![image](https://user-images.githubusercontent.com/72690360/98510560-ec02a580-2295-11eb-900d-5590ff237a79.png)
c. Kết quả mong đợi: Báo lỗi ghi nhận sai
d. Các bước để phát hiện ra lỗi:
i. #1: truy cập vào trang http://taichuc.ueh.edu.vn/
![image](https://user-images.githubusercontent.com/72690360/98510774-469c0180-2296-11eb-87e2-42127414bb89.png)
ii. #2 chuyển sang trang giới thiệu
![image](https://user-images.githubusercontent.com/72690360/98510856-6c290b00-2296-11eb-9869-c67c9e7b736b.png)
iii. #3 Cuộn trang xuống phần "Đăng ký nhận thông tin tuyển sinh"
![image](https://user-images.githubusercontent.com/72690360/98511004-adb9b600-2296-11eb-89c9-7ee3f9a17981.png)
iiii. #4 Điền các thông tin Thông tin tuyển sinh cần nhận, Họ tên, Địa chỉ mail, nhưng điền thông tin số điện thoại là chữ cái, sau đó nhấn đăng ký:
![image](https://user-images.githubusercontent.com/72690360/98510560-ec02a580-2295-11eb-900d-5590ff237a79.png)

**Comment by tatdoan2560** [comment]
Mình đã kiểm tra và xác nhận đây là lỗi đã được tìm ở khóa các anh chị trước, nhóm tìm lỗi khác giúp mình nhé!
Cảm ơn mọi người !
