### ISSUE TITLE
[Nhóm #06] - Lỗi giao diện – Có combobox nhưng khi nhấn vào thì không dropdown - ở trang http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#40]
a.	Web browser: Google Chrome 86.0.4240.183
b.	Kết quả thực tế: Có combobox nhưng khi nhấn vào thì không dropdown xuống
![image](https://user-images.githubusercontent.com/73525127/98511582-7d264c00-2297-11eb-82f4-04acb203b702.png)
c.	Kết quả mong đợi: Nhấn vào combobox sẽ dropdown 
d.	Các bước phát hiện lỗi:
i.	#1: Truy cập vào trang http://online.ueh.edu.vn/
ii.	#2: Nhấn vào button “Đăng nhập”
iii.	#3: Nhập tên đăng nhập và tài khoản và đăng nhập vào trang web
iv.	#4: Chọn mục “Xem điểm”
![image](https://user-images.githubusercontent.com/73525127/98511618-8ca59500-2297-11eb-8426-0eac1aad85a4.png)

**Comment by baolong0** [comment]
@31181025700  
Sau khi xác minh, mình xác nhận đây là tính năng của hệ thống. 
Các bạn có thể chọn năm học nhỏ hơn năm học hiện tại để hiển thị dropdown.

> QA Bảo Long
