### ISSUE TITLE
[nhóm#09] - lỗi chức năng - tự động load lại trang khi thực hiện chức năng - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#402]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: trang đã tự động load lại với URL bị thay đổi như hình
![4](https://user-images.githubusercontent.com/73509326/100749004-a8273a00-3416-11eb-8801-ed3c005a9071.PNG)
c. kết quả mong đợi: khắc phục lại lỗi tìm kiếm trên.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web [http://ctct.ueh.edu.vn/](http://ctct.ueh.edu.vn/)
ii. #2 kéo xuống phần "tra cứu điểm cộng,.." -> nhập từ khoá "select" và click tìm kiếm.
![5 - Copy](https://user-images.githubusercontent.com/73509326/100749527-59c66b00-3417-11eb-9dd0-6acdfc39730a.PNG)
iii. #3 trang đã tự load lại.
![4](https://user-images.githubusercontent.com/73509326/100749568-69de4a80-3417-11eb-8965-31a08fca0b13.PNG)

**Comment by uyenxinhdep** [comment]
Nhóm đăng lỗi tự động load lại trang nhưng lại đưa ra kết quả URL bị thay đổi (theo hình URL không thay đổi) 
-> mô tả sai nên mình không xác nhận đây là lỗi
