### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - thông tin cá nhân không được bảo mật - ở trang http://www3.youth.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#404]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: xem được thông tin người khác khi chưa đc cho phép.
![6](https://user-images.githubusercontent.com/73509326/100754262-71a0ed80-341d-11eb-900c-3b38ce20e104.PNG)
c. kết quả mong đợi: thông tin cá nhân được bảo mật.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web [http://www3.youth.ueh.edu.vn/](http://www3.youth.ueh.edu.vn/) và click chọn "tra cứu hoạt động"
![7](https://user-images.githubusercontent.com/73509326/100754738-00ae0580-341e-11eb-9d1f-96101eb07a11.PNG)
ii. #2 nhập mssv và thay đổi số cuối của mssv  bất kỳ -> click "xem kết quả".
![8](https://user-images.githubusercontent.com/73509326/100755173-787c3000-341e-11eb-836b-efbe6d2bb1d6.PNG)
iii. #3 click button " xem".
![9](https://user-images.githubusercontent.com/73509326/100755308-a19cc080-341e-11eb-9171-32260e032fa8.PNG)

**Comment by uyenxinhdep** [comment]
Trùng lỗi https://github.com/UEHMonQAQC/K41/issues/161
