### ISSUE TITLE
[Nhóm#10] Lỗi phi chức năng - Lỗi bảo mật không kết nối được cơ sở dữ liệu khi nhiều user truy cập(1000) - ở trang http://tuyensinh.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#405]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Khi quá nhiều user truy cập, trang web bị sập và các user khác không thể truy cập được.
![image](https://user-images.githubusercontent.com/73520248/100758424-14f40180-3422-11eb-987a-f76824ffea38.png)
![image](https://user-images.githubusercontent.com/73520248/100758372-06a5e580-3422-11eb-84fd-23f9c7acf53c.png)
c. Kết quả mong đợi: Truy cập trang web bình thường khi nhiều User cùng truy cập
d. Các bước phát hiện lỗi: ( sử dụng phần mềm Jmeter để giả lập user)
i. #1 Mở Phần mềm Jmeter
ii. #2 Giả lập 1000 user truy cập và như trong ảnh
![image](https://user-images.githubusercontent.com/73520248/100758673-597f9d00-3422-11eb-9409-ac870a135fe8.png)
iii. #3 Vào http request và nhập theo ảnh và ấn start 
![image](https://user-images.githubusercontent.com/73520248/100758627-4bca1780-3422-11eb-91bd-771090ab480b.png)
iv. #4 Truy cập trang http://tuyensinh.ueh.edu.vn/ để xem kết quả 
![image](https://user-images.githubusercontent.com/73520248/100758424-14f40180-3422-11eb-987a-f76824ffea38.png)

**Comment by uyenxinhdep** [comment]
Mỗi nhóm chỉ dùng phần mềm Jmeter 1 nên lỗi này sẽ tính trùng
