### ISSUE TITLE
[Nhóm#10] Lỗi phi chức năng - Lỗi bảo mật không truy cập được cơ sở dữ liệu khi quá nhiêu User truy cập (800) - ở trang http://ibr.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31181020674** [UEHMonQAQC/ST_K44#408]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Khi quá nhiều user truy cập, trang web bị sập và các user khác không thể truy cập được.
![image](https://user-images.githubusercontent.com/73520248/100765417-11647880-342a-11eb-96c2-4bbeecf3794e.png)
![image](https://user-images.githubusercontent.com/73520248/100766780-9d2ad480-342b-11eb-99fe-b6221d6fb89c.png)
c. Kết quả mong đợi: Truy cập trang web bình thường khi nhiều User cùng truy cập
d. Các bước phát hiện lỗi: ( sử dụng phần mềm Jmeter để giả lập user)
i. #1 Mở Phần mềm Jmeter
ii. #2 Giả lập 800 user truy cập và như trong ảnh
![image](https://user-images.githubusercontent.com/73520248/100766842-af0c7780-342b-11eb-9b40-df95e7cc7e66.png)
iii. #3 Vào http request và nhập theo ảnh và ấn start 
![image](https://user-images.githubusercontent.com/73520248/100766898-be8bc080-342b-11eb-8d1e-c91f154926ef.png)
iv. #4 Truy cập trang http://ibr.ueh.edu.vn/ để xem kết quả 
![image](https://user-images.githubusercontent.com/73520248/100765417-11647880-342a-11eb-96c2-4bbeecf3794e.png)

**Comment by uyenxinhdep** [comment]
Mỗi nhóm chỉ dùng phần mềm Jmeter 1 nên lỗi này sẽ tính trùng
