### ISSUE TITLE
[nhóm#09] - lỗi phi chức năng - thực hiện được chức của người khác - ở trang http://www3.youth.ueh.edu.vn/ 

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#409]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: thay đổi ngẫu nhiên mssv bất kỳ và tự mình có thể "đánh giá" của người khác mà không cần cấp quyền.
![25](https://user-images.githubusercontent.com/73509326/100771257-cac64c80-3430-11eb-8620-80f0d8397dac.PNG)
c. kết quả mong đợi: phải đăng nhập xác nhận đúng người dùng mới thực hiện được chức năng trên.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web http://www3.youth.ueh.edu.vn/ và click vào "tra cứu hoạt động".
![23](https://user-images.githubusercontent.com/73509326/100770635-10364a00-3430-11eb-83b3-8650568d0ddf.PNG)
ii. # nhập mssv bất kỳ và click xem kết quả.
![24](https://user-images.githubusercontent.com/73509326/100771082-90f54600-3430-11eb-8e60-e61409af8248.PNG)
iii. click "đánh giá các hoạt động..." và thực hiện đánh giá khi chưa được cho phép từ đúng user.
![25](https://user-images.githubusercontent.com/73509326/100771148-a66a7000-3430-11eb-93cb-e6bd673944ed.PNG)

**Comment by uyenxinhdep** [comment]
Lỗi trùng https://github.com/UEHMonQAQC/K41/issues/161
