### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng - Lỗi khả năng phục hồi trang châm - trang http://nnkt.ueh.edu.vn/

### ISSUE THREAD

**Issue by namnguyenphuong355** [UEHMonQAQC/ST_K44#410]
a. Web Browser : Google Chrome Windows 10
b. Kết quả thực tế: Khi nhiều User truy cập, trang web bị sập, khả năng phục hồi khá chậm

c. Kết quả mong đợi:
Trang web phục hồi bình thường trong 1 phút

d. d. Các bước để phát hiện lỗi: ( Sử dụng phần mềm JMeter 5.3 để giả lập User)
i. #1: Mở phần mềm JMeter
ii. #2: Giả lập User truy cập ( 500 User)
![x1](https://user-images.githubusercontent.com/73516957/100770964-6e632d00-3430-11eb-9130-bec1f5097a06.jpg)

iii. #3: Vào HTTP Request nhập Protocol (http) và nhập IP và Path (http://nnkt.ueh.edu.vn/)
![x2](https://user-images.githubusercontent.com/73516957/100771172-ae2a1480-3430-11eb-8b5f-588c8ff11e7a.jpg)

iv. #4: Vào HTTP Request Defaults nhập Protocol (http) và nhập IP và Path (http://nnkt.ueh.edu.vn/)
![x3](https://user-images.githubusercontent.com/73516957/100771195-b5e9b900-3430-11eb-9599-82cabd97b45f.jpg)

v. #5: Nhấn biểu tượng Run test
![x5](https://user-images.githubusercontent.com/73516957/100771224-c13ce480-3430-11eb-97ec-db3f6a53d99a.jpg)

vi. #6: Truy cập vào trang http://nnkt.ueh.edu.vn/ trên google chrome và xem kết quả ( phục hồi chậm)
![zzz1](https://user-images.githubusercontent.com/73516957/100771380-f5b0a080-3430-11eb-8ac7-44d2b4c69928.jpg)

![zzz2](https://user-images.githubusercontent.com/73516957/100771759-60fa7280-3431-11eb-9c03-36c4cfe7881e.jpg)

**Comment by PhucLuan** [comment]
Trùng với #391
