### ISSUE TITLE
[Nhóm#09] - Lỗi phi chức năng - Lỗi bảo mật không truy cập được cơ sở dữ liệu khi quá nhiêu User truy cập (1000) - ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#411]
a. Web Browser: Google Chrome 86.0.4240.198 (64-bit)
b. Kết quả thực tế: Khi quá nhiều user truy cập, trang web bị sập và các user khác không thể truy cập được.
![a](https://user-images.githubusercontent.com/73509326/100775559-04e61d00-3436-11eb-9623-7b38b28f06ea.png)
![s](https://user-images.githubusercontent.com/73509326/100775725-3ced6000-3436-11eb-99a9-d7ba755736cc.png)
c. Kết quả mong đợi: Truy cập trang web bình thường khi nhiều User cùng truy cập
d. Các bước phát hiện lỗi: ( sử dụng phần mềm Jmeter để giả lập user)
i. #1 Mở Phần mềm Jmeter
ii. #2 Giả lập 1000 user truy cập
 ![d](https://user-images.githubusercontent.com/73509326/100775978-8c339080-3436-11eb-8ab0-53967647ea0c.png)
iii. #3 Vào http request và nhập theo ảnh và ấn start
![f](https://user-images.githubusercontent.com/73509326/100776098-b1280380-3436-11eb-908a-d59046c41b02.png)
iv. #4 Truy cập trang https://tthtsv.ueh.edu.vn/   để xem kết quả:
![z](https://user-images.githubusercontent.com/73509326/100776192-d157c280-3436-11eb-823d-3dab2486f064.png)

**Comment by uyenxinhdep** [comment]
Xác nhận lỗi hợp lệ

**Comment by uyenxinhdep** [comment]
Lỗi trùng https://github.com/UEHMonQAQC/ST_K44/issues/345
