### ISSUE TITLE
[Nhóm #06] - Lỗi giao diện - Lỗi font chữ và dư kí hiệu - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#43]
a.	Web browser: Google Chrome 86.0.4240.183
b.	Kết quả thực tế: Font chữ "Đóng cửa sổ này" bị lỗi, dư 1 kí hiệu ":" sau 2 câu "Tên bạn" và "Email người nhận"
![image](https://user-images.githubusercontent.com/73525127/98514455-0d669000-229c-11eb-9afe-5022cc4870cc.png)
c.	Kết quả mong đợi: Font chữ “Đóng cửa sổ này” không bị lỗi, chỉ có đúng một dấu “:” cuối câu
d.	Các bước phát hiện lỗi:
i.	#1: Truy cập vào trang http://ctct.ueh.edu.vn/
ii.	#2: Nhấn vào mục “Tài liệu”
iii.	#3: Chọn mục “ISO 9001:2008”
![image](https://user-images.githubusercontent.com/73525127/98514474-16576180-229c-11eb-988c-ff3e426fb291.png)
iv.	#4: Nhấp vào kí hiệu bì thư
![image](https://user-images.githubusercontent.com/73525127/98514497-1e170600-229c-11eb-8419-502bc83f7550.png)

**Comment by baolong0** [comment]
Mình xác nhận **LỖI KHÔNG HỢP LỆ.** @31181025700 
Cụ thể : Lỗi bị trùng 
https://github.com/UEHMonQAQC/K42/issues/20
Have a nice day !
_QA_Bảo Long.
