### ISSUE TITLE
[nhóm#09] - lỗi chức năng - không có button tìm kiếm - ở trang http://daotao.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#46]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: không có button tìm kiếm, người dùng phải ấn enter trên bàn phím
![ccc](https://user-images.githubusercontent.com/73509326/98528319-b8804500-22ae-11eb-869b-037af08ff795.PNG)
c. kết quả mong muốn: có thêm button timg kiếm, người dùng có thể click trực tiếp trên giao diện.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web [http://daotao.ueh.edu.vn/](http://daotao.ueh.edu.vn/)
ii. #2 click vào mục tìm kiếm.
![ccc](https://user-images.githubusercontent.com/73509326/98528823-6c81d000-22af-11eb-931d-07cf4a14aa9a.PNG)

**Comment by uyenxinhdep** [comment]
Nhóm tìm lỗi khác giúp mình @31181025359
