### ISSUE TITLE
[nhóm#09] - lỗi giao diện - lỗi định dạng văn bản - ở trang http://ctct.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025359** [UEHMonQAQC/ST_K44#49]
a. broswer: google chrome Dành cho Windows 10/8.1/8/7 64 bit.
b. kết quả thực tế: so sánh hai trang định dạng không đồng bộ
![hh](https://user-images.githubusercontent.com/73509326/98531526-09923800-22b3-11eb-9b2a-74d035c41462.PNG)
![dagcdf](https://user-images.githubusercontent.com/73509326/98531537-0d25bf00-22b3-11eb-8f78-fdf40d57b448.PNG)
c. kết quả mong đợi: định dạng lại cho đồng bộ.
d. các bước phát hiện lỗi:
i. #1 truy cập trang web http://ctct.ueh.edu.vn/
ii. #2 click vào mục thông tin  chọn "giáo dục chính trị và tư tưởng"
![aaa](https://user-images.githubusercontent.com/73509326/98531848-7efe0880-22b3-11eb-9995-4673d4e14243.PNG)
iii. #3 click vào trang 3.
![ssss](https://user-images.githubusercontent.com/73509326/98532044-bcfb2c80-22b3-11eb-87d8-eec63dbb6b58.PNG)
iv. #4 click vào "triển khai thực hiện...." so sánh với mục "tổ chức họi nghị..."
![www](https://user-images.githubusercontent.com/73509326/98638559-364e5a00-235c-11eb-810a-5fd41344b780.PNG)
v. #5 so sánh với trang "tổ chức hội nghị..."
![f](https://user-images.githubusercontent.com/73509326/99092868-5011ca80-2604-11eb-804f-4c9b02f9ef29.PNG)

**Comment by uyenxinhdep** [comment]
Kết quả thực tế: cần dẫn đường link truy cập 2 trang đã so sánh.
Nhóm bổ sung giúp mình @31181025359

**Comment by 31181025359** [comment]
đã sửa lại
