### ISSUE TITLE
[Nhom#08]- Lỗi các đối tượng không thẳng hàng trên Header khi chuyển sang ipad (trang http://ced.ueh.edu.vn/)

### ISSUE THREAD

**Issue by namnguyenphuong355** [UEHMonQAQC/ST_K44#78]
a. Web Browser : Google Chrome cho Windows 10
b. Các bước để phát hiện lỗi:
i.    #1: Người dùng truy cập vào trang Trung tâm phát triển khởi nghiệp (http://ced.ueh.edu.vn/)
![a1](https://user-images.githubusercontent.com/73516957/98649710-77e60180-236a-11eb-9b16-324a1bb4fc8f.jpg)

ii.   #2: Người dùng thu nhỏ cửa sổ về kích cỡ ipad
![a2](https://user-images.githubusercontent.com/73516957/98649722-7ae0f200-236a-11eb-9d9a-1d3c866985d6.jpg)

iii.  #3: Quan sát các đối tượng trên thanh Header

c. Kết quả thực tế:
![a3](https://user-images.githubusercontent.com/73516957/98649740-82a09680-236a-11eb-92d8-8cfff18cb312.jpg)

d. Kết quả mong đợi
Các đối tượng trên thanh Header nằm thẳng hàng với nhau

**Comment by PhucLuan** [comment]
Test responsive phải kèm thông số kích thước màn hình. Lưu ý: chấp nhận lỗi đối với những kích thước cố định dành cho điện thoại, tablet, desktop... Không phải bất cứ kích thước nào cũng là lỗi.

**Comment by PhucLuan** [comment]
Bổ sung đường link cụ thể tới trang.

**Comment by namnguyenphuong355** [comment]
update lại
