### ISSUE TITLE
 [Nhóm #06] - Lỗi giao diện - Zoom 80% trở xuống thì khung bị lệch - ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#81]
a.	Web browser: Cốc Cốc 90.0.148
b.	Kết quả thực tế: Zoom 80% trở xuống thì khung “Cổng giao dịch điện tử UEH” bị lệch
![image](https://user-images.githubusercontent.com/73525127/98567056-1712e680-22e2-11eb-9e05-238d89ad4792.png)
c.	Kết quả mong đợi: Zoom 80% trở xuống thì khung sẽ không bị lệch
d.	Các bước phát hiện lỗi: 
i.	#1: Truy cập vào trang https://tthtsv.ueh.edu.vn/
ii.	#2: Zoom 80% trang web

**Comment by baolong0** [comment]
lỗi responsive chỉ tính ở các kích thước tiêu chuẩn nhé ! 
VD : Màn hình desktop 100%, Tablet 100%, mobile 100%,.... 

> QA Bảo Long
