### ISSUE TITLE
[Nhóm #06] - Lỗi chức năng – Sử dụng các tính năng trên navbar nhưng lại tự động đăng thoát - ở trang  http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#91]
a.	Web browser: Google Chrome 86.0.4240.183
b.	Kết quả thực tế: Tự động đăng thoát khỏi tài khoản khi nhấn vào mục “Tra cứu thông tin tốt nghiệp”
![image](https://user-images.githubusercontent.com/73525127/98623588-a8b04180-233e-11eb-8bd6-c7321c4f5afb.png)
c.	Kết quả mong đợi: Vẫn trong trạng thái đăng nhập khi chọn mục “Tra cứu thông tin tốt nghiệp”
d.	Các bước phát hiện lỗi: 
i.	#1: truy cập trang http://online.ueh.edu.vn/
ii.	#2: đăng nhập thành công
![image](https://user-images.githubusercontent.com/73525127/98623616-b5349a00-233e-11eb-974a-bd993fc0c680.png)
iii.	#3: chọn mục “Tra cứu thông tin tốt nghiệp”

**Comment by baolong0** [comment]
Lỗi bị trùng ! 
https://github.com/UEHMonQAQC/ST_K44/issues/82 
 Lỗi này đã được nhóm khác up trước ! 
team mình #91 còn team trước đã up là #82 
> QA Bảo Long
