### ISSUE TITLE
[Nhóm #06] - Lỗi chức năng – Lọc thiếu dữ liệu - ở trang  http://online.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181025700** [UEHMonQAQC/ST_K44#92]
a.	Web browser: Google Chrome 86.0.4240.183
b.	Kết quả thực tế: Lọc dữ liệu tuần 37 nhưng không ra mặc dù trong bảng thời khóa biểu hiển thị tuần 37 là có Sinh hoạt lớp hk1.1 và Tiếng Anh P1
![image](https://user-images.githubusercontent.com/73525127/98625146-ac919300-2341-11eb-8934-da67f1026d92.png)
c.	Kết quả mong đợi: Hiển thị đúng kết quả cần lọc
d.	Các bước phát hiện lỗi: 
i.	#1: truy cập trang http://online.ueh.edu.vn/
ii.	#2: Nhấn chọn mục Thời khóa biểu
iii.	#3: Chọn tuần 37 để lọc dữ liệu
![image](https://user-images.githubusercontent.com/73525127/98625161-b3200a80-2341-11eb-8953-527d11d417af.png)

**Comment by baolong0** [comment]
Lỗi bị trùng ! 
https://github.com/UEHMonQAQC/ST_K44/issues/90 
 thứ tự up lỗi của team mình là 92. Tức là lỗi này đã được up đúng format trước đó nên không được tính ! 
Gudluck
> QA Bảo Long
