### ISSUE TITLE
[Nhóm#05] - Lỗi chức năng -Lỗi click vào mục danh mục không hiển thị các danh mục - ở trang https://tthtsv.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31181024008** [UEHMonQAQC/ST_K44#98]
a. Web Browser: Google Chrome 86.0.4240.183
b. Kết quả thực tế: click vào mục danh mục không hiển thị các danh mục
c. Kết quả mong muốn: click vào sẽ hiện thị các danh mục
d. Các bước phát hiện lỗi:
i. #1: Truy cập vào trang https://tthtsv.ueh.edu.vn/
ii. #2: Thu nhỏ ứng dụng web
iii. #3 click vào danh mục không hiển thị các danh mục trang chủ, giới thiệu,…
![2](https://user-images.githubusercontent.com/73530783/98626393-3cd0d780-2344-11eb-93e1-b3562402405e.jpg)

**Comment by baolong0** [comment]
Lỗi bị trùng rồi !
@31181024008 

chi tiết : https://github.com/UEHMonQAQC/ST_K44/issues/72
> QA Bảo Long

**Comment by baolong0** [comment]
lỗi trùng, Nhưng đúng format trước ! 
https://github.com/UEHMonQAQC/ST_K44/issues/72

**Comment by baolong0** [comment]
Sau khi xác minh thì mình xác định nhóm mình bị trùng lỗi nhé ! 

> QA Bảo Long
